"""Real-Postgres seed tests for WU-3B (``scripts.seed_apollo_learner_model``).

The seeder converts the hand-authored bernoulli source files into Layer-1 rows
(``app.learner_entities`` + ``internal.entity_prerequisites`` + aliases) and
annotates the bernoulli problems' reference solutions with entity links + a
declared path so the §6.1 validation contract passes.

DB-13 (``docs/_archive/plans/...db-13...``): the seeder no longer reads
``misconceptions.json`` at all, and ``app.learner_entities``' target DDL kind
CHECK (``learner_entities__kind__check``) has no ``'misconception'`` value —
``misc.*`` entities + their opposes-link are NEVER minted or persisted
(adjudicated ruling, see ``apollo/persistence/learner_model_seed.py``'s
``misconceptions_to_entities`` docstring). Misconception nodes are excluded
from the Postgres Layer-1 skill inventory entirely.

Harness mirrors ``tests/database/test_apollo_learner_model_migration.py``: the
session ``_pg_url`` pgvector container, a content-scoped migration chain + 026
applied to a fresh database, with ``auth.users`` / ``aita_search_spaces`` stubs,
the target ``app.courses`` / ``app.concepts`` / ``app.problems`` tables, and
(DB-13) the target ``app.learner_entities`` / ``internal.entity_prerequisites``
tables the seeder now actually writes to (columns mirrored verbatim from
``supabase/migrations/20260717035041_create_app_schema_v1.sql`` — see
``_STUB_DDL`` below; ``app.learner_state`` / ``app.mastery_events`` are NOT
stubbed here since nothing in the seeder or these tests touches them).
UNLIKE WU-3A this seeds matching legacy curriculum rows (for the historical
migration FKs) and target curriculum rows (which the seeder reads), then runs
``seed`` through SQLAlchemy and asserts on the resulting rows.

Each test builds its OWN fresh database so the seeder's commit + idempotency
second-run can be observed without per-test transaction rollback interfering.
"""

from __future__ import annotations

import asyncio
import json
import re
from pathlib import Path

import asyncpg
import pytest
import pytest_asyncio
from sqlalchemy.engine import make_url

from apollo.persistence.learner_model_seed import SeedError, validate_reference_graph
from scripts.seed_apollo_learner_model import main
from scripts.seed_apollo_learner_model import seed as _seed

pytestmark = pytest.mark.integration

_REPO = Path(__file__).resolve().parents[2]
MIGRATIONS_DIR = _REPO / "database" / "migrations"
_BERNOULLI = _REPO / "apollo" / "subjects" / "fluid_mechanics" / "concepts" / "bernoulli_principle"


async def seed(database_url: str, **kwargs):
    """Run the production seeder without rewriting repository fixtures.

    Disk write-back has dedicated coverage against ``tmp_path`` in
    ``apollo/persistence/tests/test_learner_model_seed_generic.py``. These
    integration tests only exercise database effects, so a future bare
    ``seed()`` call must remain side-effect-free outside the test database.
    """
    kwargs.setdefault("write_disk", False)
    return await _seed(database_url, **kwargs)


# Same FK stubs + content-scoped chain selection as the WU-3A harness.  The
# seeder resolves curriculum through the target ORM, so this isolated legacy
# migration chain must also provision the target curriculum tables it reads,
# PLUS (DB-13) the target app.learner_entities / internal.entity_prerequisites
# tables the seeder writes Layer-1 rows into (apollo_kg_entities /
# apollo_entity_prereqs, minted by the 026 migration below, are legacy tables
# nothing in the current seed path reads or writes any more).
_STUB_DDL = """
CREATE SCHEMA IF NOT EXISTS auth;
CREATE TABLE auth.users (id UUID PRIMARY KEY);
CREATE TABLE aita_search_spaces (id SERIAL PRIMARY KEY);
CREATE SCHEMA IF NOT EXISTS app;
CREATE SCHEMA IF NOT EXISTS internal;
CREATE TABLE app.courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    subject_name TEXT NOT NULL,
    current_week SMALLINT NOT NULL DEFAULT 1,
    retrieval_weights JSONB NOT NULL DEFAULT '{}'::jsonb,
    retrieval_weight_min REAL NOT NULL DEFAULT 0,
    retrieval_weight_max REAL NOT NULL DEFAULT 1,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT courses__current_week__check CHECK (current_week BETWEEN 1 AND 16),
    CONSTRAINT courses__retrieval_weight_bounds__check CHECK (
        0 <= retrieval_weight_min
        AND retrieval_weight_min <= retrieval_weight_max
        AND retrieval_weight_max <= 1
    ),
    CONSTRAINT courses__retrieval_weights__object_check
        CHECK (jsonb_typeof(retrieval_weights) = 'object'),
    CONSTRAINT courses__metadata__object_check
        CHECK (jsonb_typeof(metadata) = 'object')
);
CREATE TABLE app.concepts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    subject_slug TEXT NOT NULL,
    subject_display_name TEXT NOT NULL,
    slug TEXT NOT NULL,
    display_name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    canonical_symbols TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    symbol_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    normalization_map JSONB NOT NULL DEFAULT '{}'::jsonb,
    parser_prompt_template TEXT NOT NULL DEFAULT '',
    solver_config JSONB NOT NULL DEFAULT '{}'::jsonb,
    parser_config JSONB NOT NULL DEFAULT '{}'::jsonb,
    forbidden_named_laws TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT concepts_course_subject_slug_key
        UNIQUE (course_id, subject_slug, slug)
);
CREATE TABLE app.problems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    concept_id BIGINT NOT NULL REFERENCES app.concepts(id) ON DELETE CASCADE,
    problem_code TEXT NOT NULL,
    difficulty TEXT NOT NULL,
    problem_text TEXT NOT NULL,
    given_values JSONB NOT NULL DEFAULT '{}'::jsonb,
    target_unknown TEXT NOT NULL DEFAULT '',
    reference_solution JSONB NOT NULL,
    payload_extra JSONB NOT NULL DEFAULT '{}'::jsonb,
    tier SMALLINT NOT NULL DEFAULT 1,
    solution_source TEXT,
    provenance JSONB NOT NULL DEFAULT '{}'::jsonb,
    quarantined_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT problems_concept_code_key UNIQUE (concept_id, problem_code)
);
-- DB-13 target DDL (columns/constraints mirrored verbatim from
-- supabase/migrations/20260717035041_create_app_schema_v1.sql) — the seeder's
-- LearnerEntity / EntityPrereq ORM models map onto these. 'misconception' is
-- deliberately ABSENT from the kind CHECK (DB-13/A6 ruling): the seeder never
-- attempts to write one, and test_learner_entities_kind_check.py separately
-- proves the CHECK rejects one on real Postgres.
CREATE TABLE app.learner_entities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    concept_id BIGINT NOT NULL REFERENCES app.concepts(id) ON DELETE CASCADE,
    canonical_key TEXT NOT NULL,
    kind TEXT NOT NULL,
    display_name TEXT NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    aliases TEXT[] NOT NULL DEFAULT '{}'::text[],
    scope_summary TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (concept_id, canonical_key),
    CONSTRAINT learner_entities__kind__check
        CHECK (kind IN ('concept', 'equation', 'condition', 'definition', 'procedure', 'variable')),
    CONSTRAINT learner_entities__payload__object_check CHECK (jsonb_typeof(payload) = 'object')
);
CREATE TABLE internal.entity_prerequisites (
    course_id BIGINT NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    from_entity_id BIGINT NOT NULL REFERENCES app.learner_entities(id) ON DELETE CASCADE,
    to_entity_id BIGINT NOT NULL REFERENCES app.learner_entities(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (from_entity_id, to_entity_id),
    CONSTRAINT entity_prerequisites__not_self__check CHECK (from_entity_id <> to_entity_id)
);
"""
_TOUCHES_TARGETS = re.compile(
    r"(CREATE TABLE IF NOT EXISTS|CREATE TABLE|ALTER TABLE)\s+"
    r"apollo_(subjects|concepts|problem_attempts)\b"
)
_MIGRATION_026 = MIGRATIONS_DIR / "026_apollo_learner_model.sql"
# Migration 030 (WU-3B2a) ALTERs apollo_concept_problems with tier/solution_source/
# provenance/quarantined_at/search_space_id. The learner-model seeder selects through
# the ProblemRecord ORM, which now declares those columns, so the seeder's
# `SELECT ... tier ...` errors unless the harness table carries them. 030 depends on
# 026 (its concept->subject backfill-join reads apollo_subjects.search_space_id, added
# by 026) so it is applied AFTER 026, not in the auto-built chain.
_MIGRATION_030 = MIGRATIONS_DIR / "030_apollo_autoprovisioning.sql"
# Later migrations that ALTER apollo_problem_attempts but DEPEND on 026's columns
# must be excluded: this harness applies 026 LAST (separately), so a migration that
# references 026's additions would run before 026 here and fail. 028 (WU-5B3a-0)
# adds a partial index whose predicate references `learner_update_pending` — a
# column 026 creates — so it is excluded here. 028 has its own forward-chain test
# (test_apollo_learner_janitor_migration.py); the seeder does not need its columns.
# 030 is applied separately after 026 (see _apply_chain), so it too is excluded from
# the auto-built chain.
_EXCLUDE_FROM_CHAIN = frozenset(
    {
        _MIGRATION_026.name,
        _MIGRATION_030.name,
        "028_apollo_learner_janitor.sql",
        "046_apollo_solution_source_llm_paired.sql",
    }
)


def _chain_migrations() -> list[Path]:
    return [
        path
        for path in sorted(MIGRATIONS_DIR.glob("*.sql"))
        if path.name not in _EXCLUDE_FROM_CHAIN
        and _TOUCHES_TARGETS.search(path.read_text(encoding="utf-8"))
    ]


def _plain_dsn(sqlalchemy_url: str, database: str) -> str:
    url = make_url(sqlalchemy_url).set(drivername="postgresql", database=database)
    return url.render_as_string(hide_password=False)


def _asyncpg_dsn_to_sqlalchemy(plain_dsn: str) -> str:
    return (
        make_url(plain_dsn)
        .set(drivername="postgresql+asyncpg")
        .render_as_string(hide_password=False)
    )


async def _create_db(admin_dsn: str, name: str) -> None:
    admin = await asyncpg.connect(admin_dsn)
    try:
        await admin.execute(f'DROP DATABASE IF EXISTS "{name}"')
        await admin.execute(f'CREATE DATABASE "{name}"')
    finally:
        await admin.close()


async def _apply_chain(dsn: str) -> None:
    conn = await asyncpg.connect(dsn)
    try:
        await conn.execute(_STUB_DDL)
        for migration in _chain_migrations():
            await conn.execute(migration.read_text(encoding="utf-8"))
        await conn.execute(_MIGRATION_026.read_text(encoding="utf-8"))
        # 030 (WU-3B2a) adds the tier/* columns the ProblemRecord ORM now selects;
        # it must apply after 026 (its backfill-join reads apollo_subjects.search_space_id).
        await conn.execute(_MIGRATION_030.read_text(encoding="utf-8"))
    finally:
        await conn.close()


def _load_problem(n: int) -> dict:
    return json.loads(
        (_BERNOULLI / "problems" / f"problem_{n:02d}.json").read_text(encoding="utf-8")
    )


async def _seed_space(conn: asyncpg.Connection) -> int:
    course_id = await conn.fetchval("INSERT INTO aita_search_spaces DEFAULT VALUES RETURNING id")
    await conn.execute(
        "INSERT INTO app.courses (id, name, slug, subject_name) "
        "VALUES ($1, 'Test Course', $2, 'Fluid Mechanics')",
        course_id,
        f"test-course-{course_id}",
    )
    return course_id


async def _seed_one_course(conn: asyncpg.Connection) -> int:
    """Create one bootstrap course + its bernoulli curriculum. Returns concept_id."""
    space_id = await _seed_space(conn)
    return await _seed_bernoulli_curriculum(conn, space_id)


async def _seed_bernoulli_curriculum(
    conn: asyncpg.Connection, space_id: int, *, subject_slug: str = "fluid_mechanics"
) -> int:
    """Insert the bernoulli subject/concept/problems the seeder reads. Returns
    the bernoulli concept_id. All 5 problems are attached to the bernoulli
    concept (the WU-3B reference fixture set).

    ``subject_slug`` is parametrized because ``apollo_subjects.slug`` carries a
    GLOBAL UNIQUE constraint (migration 018), so a two-course test cannot give
    both courses a subject named ``fluid_mechanics``. The seeder resolves the
    concept by (search_space_id, concept.slug='bernoulli_principle') regardless
    of the subject slug, so distinct subject slugs do not change its behavior;
    the bernoulli CONCEPT slug stays the same under each course (concept slug
    uniqueness is per-subject, not global)."""
    subject_id = await conn.fetchval(
        "INSERT INTO apollo_subjects (slug, display_name, search_space_id) "
        "VALUES ($1, 'Fluid Mechanics', $2) RETURNING id",
        subject_slug,
        space_id,
    )
    concept_id = await conn.fetchval(
        "INSERT INTO apollo_concepts (subject_id, slug, display_name) "
        "VALUES ($1, 'bernoulli_principle', 'Bernoulli''s Principle') RETURNING id",
        subject_id,
    )
    await conn.execute(
        "INSERT INTO app.concepts "
        "(id, course_id, subject_slug, subject_display_name, slug, display_name) "
        "VALUES ($1, $2, $3, 'Fluid Mechanics', "
        "'bernoulli_principle', 'Bernoulli''s Principle')",
        concept_id,
        space_id,
        subject_slug,
    )
    for n in range(1, 6):
        payload = _load_problem(n)
        problem_id = await conn.fetchval(
            "INSERT INTO apollo_concept_problems "
            "(concept_id, problem_code, difficulty, payload) "
            "VALUES ($1,$2,$3,$4) RETURNING id",
            concept_id,
            payload["id"],
            payload.get("difficulty", "intro"),
            json.dumps(payload),
        )
        known = {
            "id",
            "database_id",
            "concept_id",
            "difficulty",
            "problem_text",
            "given_values",
            "target_unknown",
            "reference_solution",
        }
        await conn.execute(
            "INSERT INTO app.problems "
            "(id, course_id, concept_id, problem_code, difficulty, problem_text, "
            "given_values, target_unknown, reference_solution, payload_extra, tier) "
            "VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,2)",
            problem_id,
            space_id,
            concept_id,
            payload["id"],
            payload.get("difficulty", "intro"),
            payload["problem_text"],
            json.dumps(payload.get("given_values", {})),
            payload.get("target_unknown", ""),
            json.dumps({"version": 1, "steps": payload["reference_solution"]}),
            json.dumps({key: value for key, value in payload.items() if key not in known}),
        )
    return concept_id


@pytest_asyncio.fixture
async def seeded_db(_pg_url: str):
    """Async builder: create a fresh migrated DB, seed bernoulli curriculum via
    the supplied coroutine, and return (sqlalchemy_dsn, plain_dsn). Cleans up the
    created databases afterwards."""
    base_db = make_url(_pg_url).database
    admin_dsn = _plain_dsn(_pg_url, base_db)
    created: list[str] = []

    async def _build(seed_curriculum) -> tuple[str, str]:
        name = f"wu3b_seed_{len(created)}"
        created.append(name)
        plain = _plain_dsn(_pg_url, name)
        await _create_db(admin_dsn, name)
        await _apply_chain(plain)
        conn = await asyncpg.connect(plain)
        try:
            await seed_curriculum(conn)
        finally:
            await conn.close()
        return _asyncpg_dsn_to_sqlalchemy(plain), plain

    try:
        yield _build
    finally:
        admin = await asyncpg.connect(admin_dsn)
        try:
            for name in created:
                await admin.execute(f'DROP DATABASE IF EXISTS "{name}"')
        finally:
            await admin.close()


async def _fetch(plain_dsn: str, query: str, *args):
    conn = await asyncpg.connect(plain_dsn)
    try:
        return await conn.fetch(query, *args)
    finally:
        await conn.close()


async def _fetchval(plain_dsn: str, query: str, *args):
    conn = await asyncpg.connect(plain_dsn)
    try:
        return await conn.fetchval(query, *args)
    finally:
        await conn.close()


async def _fetch_target_problem_payloads(plain_dsn: str, concept_id: int):
    """Reconstruct public payloads from the target table's split columns."""
    return await _fetch(
        plain_dsn,
        "SELECT payload_extra || jsonb_build_object("
        "'id', problem_code, 'difficulty', difficulty, 'problem_text', problem_text, "
        "'given_values', given_values, 'target_unknown', target_unknown, "
        "'reference_solution', reference_solution->'steps') AS payload "
        "FROM app.problems WHERE concept_id=$1 ORDER BY id",
        concept_id,
    )


# ---------------------------------------------------------------------------
# Entities / prereqs / aliases
# ---------------------------------------------------------------------------


async def test_seed_creates_concept_entities_one_per_dag_node(seeded_db):
    sa_dsn, plain = await seeded_db(_seed_one_course)
    await seed(sa_dsn)

    concept_id = await _fetchval(
        plain, "SELECT id FROM app.concepts WHERE slug='bernoulli_principle'"
    )
    n = await _fetchval(
        plain,
        "SELECT count(*) FROM app.learner_entities WHERE concept_id=$1 AND kind='concept'",
        concept_id,
    )
    assert n == 14
    present = await _fetchval(
        plain,
        "SELECT count(*) FROM app.learner_entities "
        "WHERE concept_id=$1 AND canonical_key='concept.bernoulli_principle'",
        concept_id,
    )
    assert present == 1


async def test_seed_creates_variable_entities_from_symbols(seeded_db):
    sa_dsn, plain = await seeded_db(_seed_one_course)
    await seed(sa_dsn)
    concept_id = await _fetchval(
        plain, "SELECT id FROM app.concepts WHERE slug='bernoulli_principle'"
    )
    n = await _fetchval(
        plain,
        "SELECT count(*) FROM app.learner_entities WHERE concept_id=$1 AND kind='variable'",
        concept_id,
    )
    assert n == 8  # 7 canonical + var.q
    display = await _fetchval(
        plain,
        "SELECT display_name FROM app.learner_entities WHERE concept_id=$1 AND canonical_key='var.P'",
        concept_id,
    )
    assert display == "pressure"


async def test_seed_creates_prereq_edges_one_per_dag_edge(seeded_db):
    sa_dsn, plain = await seeded_db(_seed_one_course)
    await seed(sa_dsn)
    concept_id = await _fetchval(
        plain, "SELECT id FROM app.concepts WHERE slug='bernoulli_principle'"
    )
    n = await _fetchval(
        plain,
        "SELECT count(*) FROM internal.entity_prerequisites p "
        "JOIN app.learner_entities e ON e.id = p.from_entity_id "
        "WHERE e.concept_id=$1",
        concept_id,
    )
    assert n == 16
    # The bernoulli -> energy_conservation edge resolves to real entity ids.
    edge = await _fetchval(
        plain,
        "SELECT count(*) FROM internal.entity_prerequisites p "
        "JOIN app.learner_entities ef ON ef.id = p.from_entity_id "
        "JOIN app.learner_entities et ON et.id = p.to_entity_id "
        "WHERE ef.canonical_key='concept.bernoulli_principle' "
        "AND et.canonical_key='concept.energy_conservation_fluid' "
        "AND ef.concept_id=$1",
        concept_id,
    )
    assert edge == 1


async def test_seed_populates_aliases_from_normalization_map(seeded_db):
    sa_dsn, plain = await seeded_db(_seed_one_course)
    await seed(sa_dsn)
    concept_id = await _fetchval(
        plain, "SELECT id FROM app.concepts WHERE slug='bernoulli_principle'"
    )
    p_aliases = await _fetchval(
        plain,
        "SELECT aliases FROM app.learner_entities WHERE concept_id=$1 AND canonical_key='var.P'",
        concept_id,
    )
    # DB-13: aliases is TEXT[] on the target DDL (was JSONB pre-cleanup) — asyncpg
    # decodes a Postgres array to a native Python list, no json.loads needed.
    assert "static pressure" in p_aliases
    rows = await _fetch(
        plain,
        "SELECT aliases FROM app.learner_entities WHERE concept_id=$1 AND kind='variable'",
        concept_id,
    )
    total = sum(len(r["aliases"]) for r in rows)
    assert total == 23


# ---------------------------------------------------------------------------
# Misconceptions: DB-13 adjudicated ruling — NEVER minted or persisted
# ---------------------------------------------------------------------------


async def test_seed_does_not_create_misconception_entities(seeded_db):
    """DB-13/A6 ruling: the seeder never reads ``misconceptions.json`` (see
    ``scripts/seed_apollo_learner_model.py``'s ``_collect_entity_specs``) and
    ``app.learner_entities``' target DDL kind CHECK
    (``learner_entities__kind__check``) has no ``'misconception'`` value.

    This replaces the pre-DB-13 assertion that ``misc.*`` entities + an
    opposes-link were minted (``misc.density_ignored`` opposing
    ``cond.incompressibility``) — that behavior was deliberately removed;
    misconceptions are excluded from the Postgres Layer-1 skill inventory
    entirely. The surviving kinds (concept/variable/equation/condition/
    procedure/definition) are still minted normally."""
    sa_dsn, plain = await seeded_db(_seed_one_course)
    await seed(sa_dsn)
    concept_id = await _fetchval(
        plain, "SELECT id FROM app.concepts WHERE slug='bernoulli_principle'"
    )
    misconception_count = await _fetchval(
        plain,
        "SELECT count(*) FROM app.learner_entities WHERE concept_id=$1 AND kind='misconception'",
        concept_id,
    )
    assert misconception_count == 0

    # No row anywhere carries the legacy misconception canonical_key either.
    density_ignored = await _fetchval(
        plain,
        "SELECT count(*) FROM app.learner_entities "
        "WHERE concept_id=$1 AND canonical_key='misc.density_ignored'",
        concept_id,
    )
    assert density_ignored == 0

    kinds = {
        r["kind"]
        for r in await _fetch(
            plain,
            "SELECT DISTINCT kind FROM app.learner_entities WHERE concept_id=$1",
            concept_id,
        )
    }
    assert "misconception" not in kinds
    # The surviving kinds are still minted from the concept dag, canonical
    # symbols, reference solutions, and the bernoulli authored definition.
    assert kinds == {"concept", "variable", "equation", "condition", "procedure", "definition"}


# ---------------------------------------------------------------------------
# Reference-node links + declared paths + §6.1 validation
# ---------------------------------------------------------------------------


async def test_seed_links_every_reference_node_to_an_entity(seeded_db):
    """Every reference-solution step gets linked to a real ``app.learner_entities``
    row. DB-13: ``keys`` never contains a ``kind='misconception'`` canonical_key
    (none are ever minted, see ``test_seed_does_not_create_misconception_entities``)
    — reference-solution steps never carry a misconception ``entry_type`` either
    (misconceptions come from the separate, no-longer-read ``misconceptions.json``,
    never from a problem's ``reference_solution``), so misconception reference
    nodes are excluded from this every-node-links assertion by construction on
    both sides of the comparison."""
    sa_dsn, plain = await seeded_db(_seed_one_course)
    await seed(sa_dsn)
    concept_id = await _fetchval(
        plain, "SELECT id FROM app.concepts WHERE slug='bernoulli_principle'"
    )
    keys = {
        r["canonical_key"]
        for r in await _fetch(
            plain,
            "SELECT canonical_key FROM app.learner_entities "
            "WHERE concept_id=$1 AND kind != 'misconception'",
            concept_id,
        )
    }
    rows = await _fetch_target_problem_payloads(plain, concept_id)
    assert len(rows) == 5
    for row in rows:
        payload = json.loads(row["payload"])
        for step in payload["reference_solution"]:
            if step.get("entry_type") == "misconception":
                continue  # excluded: never minted, never entity-linked (DB-13)
            assert step.get("entity_key"), f"unlinked step {step.get('id')}"
            assert step["entity_key"] in keys


async def test_seed_declares_one_path_per_problem(seeded_db):
    sa_dsn, plain = await seeded_db(_seed_one_course)
    await seed(sa_dsn)
    concept_id = await _fetchval(
        plain, "SELECT id FROM app.concepts WHERE slug='bernoulli_principle'"
    )
    rows = await _fetch_target_problem_payloads(plain, concept_id)
    for row in rows:
        payload = json.loads(row["payload"])
        paths = payload["declared_paths"]
        assert len(paths) >= 1
        assert len(paths[0]) >= 1
        node_ids = {s["id"] for s in payload["reference_solution"]}
        assert set(paths[0]) == node_ids


async def test_seeded_problem_passes_reference_graph_validation(seeded_db):
    """The binding WU-4A gate: every seeded problem passes §6.1 validation."""
    sa_dsn, plain = await seeded_db(_seed_one_course)
    await seed(sa_dsn)
    concept_id = await _fetchval(
        plain, "SELECT id FROM app.concepts WHERE slug='bernoulli_principle'"
    )
    rows = await _fetch_target_problem_payloads(plain, concept_id)
    assert len(rows) == 5
    for row in rows:
        payload = json.loads(row["payload"])
        result = validate_reference_graph(payload)
        assert result.ok is True, f"{payload['id']} failed §6.1: {result.errors}"


# ---------------------------------------------------------------------------
# Idempotency + dedup
# ---------------------------------------------------------------------------


async def test_seed_is_idempotent_second_run_inserts_nothing(seeded_db):
    sa_dsn, plain = await seeded_db(_seed_one_course)
    first = await seed(sa_dsn)
    assert first["entities_inserted"] > 0

    concept_id = await _fetchval(
        plain, "SELECT id FROM app.concepts WHERE slug='bernoulli_principle'"
    )
    entities_before = await _fetchval(
        plain,
        "SELECT count(*) FROM app.learner_entities WHERE concept_id=$1",
        concept_id,
    )
    prereqs_before = await _fetchval(
        plain,
        "SELECT count(*) FROM internal.entity_prerequisites p "
        "JOIN app.learner_entities e ON e.id=p.from_entity_id WHERE e.concept_id=$1",
        concept_id,
    )

    second = await seed(sa_dsn)  # must raise nothing
    assert second["entities_inserted"] == 0
    assert second["prereqs_inserted"] == 0

    entities_after = await _fetchval(
        plain,
        "SELECT count(*) FROM app.learner_entities WHERE concept_id=$1",
        concept_id,
    )
    prereqs_after = await _fetchval(
        plain,
        "SELECT count(*) FROM internal.entity_prerequisites p "
        "JOIN app.learner_entities e ON e.id=p.from_entity_id WHERE e.concept_id=$1",
        concept_id,
    )
    assert entities_after == entities_before
    assert prereqs_after == prereqs_before


async def test_dedup_shared_reference_entities_single_row(seeded_db):
    sa_dsn, plain = await seeded_db(_seed_one_course)
    await seed(sa_dsn)
    concept_id = await _fetchval(
        plain, "SELECT id FROM app.concepts WHERE slug='bernoulli_principle'"
    )
    # continuity appears in problems 01/03/05 but mints ONE entity.
    n = await _fetchval(
        plain,
        "SELECT count(*) FROM app.learner_entities "
        "WHERE concept_id=$1 AND canonical_key='eq.continuity'",
        concept_id,
    )
    assert n == 1


# ---------------------------------------------------------------------------
# Course-scoping + error path
# ---------------------------------------------------------------------------


async def test_seed_is_course_scoped_two_courses_do_not_collide(seeded_db):
    async def _two_courses(conn):
        s1 = await _seed_space(conn)
        await _seed_bernoulli_curriculum(conn, s1, subject_slug="fluid_mechanics_c1")
        s2 = await _seed_space(conn)
        await _seed_bernoulli_curriculum(conn, s2, subject_slug="fluid_mechanics_c2")

    sa_dsn, plain = await seeded_db(_two_courses)
    # Resolve the two spaces + their bernoulli concepts.
    spaces = [r["id"] for r in await _fetch(plain, "SELECT id FROM aita_search_spaces ORDER BY id")]
    assert len(spaces) == 2
    # Each course's DB subject slug is distinct (global UNIQUE), but both share the
    # physical bernoulli source dir, so source_subject_slug pins it to fluid_mechanics.
    await seed(
        sa_dsn,
        subject_slug="fluid_mechanics_c1",
        source_subject_slug="fluid_mechanics",
        search_space_id=spaces[0],
    )
    await seed(
        sa_dsn,
        subject_slug="fluid_mechanics_c2",
        source_subject_slug="fluid_mechanics",
        search_space_id=spaces[1],
    )

    for space_id in spaces:
        concept_id = await _fetchval(
            plain,
            "SELECT id FROM app.concepts WHERE course_id=$1 AND slug='bernoulli_principle'",
            space_id,
        )
        n = await _fetchval(
            plain,
            "SELECT count(*) FROM app.learner_entities WHERE concept_id=$1 AND kind='concept'",
            concept_id,
        )
        assert n == 14

    # Deleting course-1 cascades only course-1's entities.
    c2_concept = await _fetchval(
        plain,
        "SELECT id FROM app.concepts WHERE course_id=$1 AND slug='bernoulli_principle'",
        spaces[1],
    )
    c2_before = await _fetchval(
        plain,
        "SELECT count(*) FROM app.learner_entities WHERE concept_id=$1",
        c2_concept,
    )
    conn = await asyncpg.connect(plain)
    try:
        await conn.execute("DELETE FROM aita_search_spaces WHERE id=$1", spaces[0])
    finally:
        await conn.close()
    c2_after = await _fetchval(
        plain,
        "SELECT count(*) FROM app.learner_entities WHERE concept_id=$1",
        c2_concept,
    )
    assert c2_after == c2_before and c2_after > 0
    # course-1's subject (and thus its entity chain) is gone.
    c1_subjects = await _fetchval(
        plain,
        "SELECT count(*) FROM apollo_subjects WHERE search_space_id=$1",
        spaces[0],
    )
    assert c1_subjects == 0


async def test_seed_errors_when_concept_missing(seeded_db):
    async def _space_only(conn):
        await _seed_space(conn)  # a course but NO bernoulli concept

    sa_dsn, _plain = await seeded_db(_space_only)
    with pytest.raises(SeedError):
        await seed(sa_dsn)


async def test_seed_errors_when_no_courses(seeded_db):
    """Default search_space_id resolution against an empty app.courses
    raises SeedError (no course to attribute the seed to)."""

    async def _nothing(conn):  # no space, no curriculum
        return None

    sa_dsn, _plain = await seeded_db(_nothing)
    with pytest.raises(SeedError):
        await seed(sa_dsn)


async def test_seed_dry_run_rolls_back(seeded_db):
    """A dry run computes the same stats but writes nothing to the DB."""
    sa_dsn, plain = await seeded_db(_seed_one_course)
    stats = await seed(sa_dsn, dry_run=True, write_disk=False)
    assert stats["entities_inserted"] > 0  # would-be inserts counted
    concept_id = await _fetchval(
        plain, "SELECT id FROM app.concepts WHERE slug='bernoulli_principle'"
    )
    rows = await _fetchval(
        plain,
        "SELECT count(*) FROM app.learner_entities WHERE concept_id=$1",
        concept_id,
    )
    assert rows == 0  # rolled back


def test_main_dry_run_happy_path(_pg_url, capsys):
    """main() with --dry-run + --no-write-disk against a seeded DB returns 0 and
    prints the stats dict (covers the CLI happy path without mutating rows).

    This test is SYNCHRONOUS on purpose: main() calls asyncio.run internally, so
    it must run with NO event loop already running. A sync test gives main its
    own clean loop (no nested loop / worker thread). The DB is built + asserted
    via asyncio.run on a self-contained coroutine."""
    base_db = make_url(_pg_url).database
    admin_dsn = _plain_dsn(_pg_url, base_db)
    name = "wu3b_main_dry_run"
    plain = _plain_dsn(_pg_url, name)
    sa_dsn = _asyncpg_dsn_to_sqlalchemy(plain)

    async def _build_and_count() -> int:
        await _create_db(admin_dsn, name)
        await _apply_chain(plain)
        conn = await asyncpg.connect(plain)
        try:
            await _seed_one_course(conn)
        finally:
            await conn.close()
        return 0

    async def _count_entities() -> int:
        concept_id = await _fetchval(
            plain, "SELECT id FROM app.concepts WHERE slug='bernoulli_principle'"
        )
        return await _fetchval(
            plain,
            "SELECT count(*) FROM app.learner_entities WHERE concept_id=$1",
            concept_id,
        )

    async def _drop() -> None:
        admin = await asyncpg.connect(admin_dsn)
        try:
            await admin.execute(f'DROP DATABASE IF EXISTS "{name}"')
        finally:
            await admin.close()

    try:
        asyncio.run(_build_and_count())
        rc = main(["--database-url", sa_dsn, "--dry-run", "--no-write-disk"])
        assert rc == 0
        out = capsys.readouterr().out
        assert "seeded:" in out
        # Dry run -> no rows written.
        assert asyncio.run(_count_entities()) == 0
    finally:
        asyncio.run(_drop())
