"""P3.2 level-4 ceiling arithmetic — BUILT DARK (`.planning/specs/
2026-08-12-apollo-p32-wrongness-signal-design.md` §2.3 L4, §2.5).

Nothing in production reaches this arithmetic: `compute_topic_score`'s new
keywords default to ``misconceptions=None`` / ``ceiling_active=False``, which is
the level-0/1/2 call and returns the pre-feature result. `PRE_FEATURE_DIGESTS`
below is the executable proof — the digests were generated by running
``_topic_score_corpus.inertness_corpus()`` against the PRE-FEATURE
``topic_score.py`` (``origin/staging`` @ 7c51fbe) and pasted here unchanged.
P-1/P-2/P-3 are the student-protective properties that gate any future
activation.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from typing import Any

import pytest

from apollo.ontology import KGGraph
from apollo.overseer.aside_penalty import apply_aside_caps
from apollo.overseer.rubric import score_to_letter
from apollo.overseer.tests._topic_score_corpus import digest, equation, inertness_corpus
from apollo.overseer.topic_score import (
    CEILING_UNCORRECTED,
    REFERENCE_TEXT_CREDIT_THRESHOLD,
    UNPROBED_CREDIT_KEEP_THRESHOLD,
    compute_centrality,
    compute_topic_score,
)
from apollo.overseer.topic_score_serialize import serialize_topic_score

pytestmark = pytest.mark.unit


@dataclass(frozen=True)
class _Finding:
    """A structural ``MisconceptionSpec`` — the shape ``wrongness``'s
    ``WrongnessFinding`` satisfies. ``topic_score`` must never import the
    wrongness types (seam S7), so the test supplies its own duck."""

    node_id: str
    quote: str
    resolved: bool = False


# sha256 of ``json.dumps(serialize_topic_score(result), sort_keys=True)`` per
# corpus case, generated against the PRE-FEATURE module before the ceiling
# keywords existed. Drift here means the dark build stopped being dark — do NOT
# regenerate these to make the test pass.
PRE_FEATURE_DIGESTS: dict[str, str] = {
    "binary_per_step_half": "43508a7aa95ab4fbf6fe435adb8495c279658d00995e6648e2d127c69f207916",
    "partial_credit_with_span": "60a988b84107e732285f3931c3dd77f46465b0e7f2fb462ef830fc3800bce92f",
    "hoot_assisted_mixed": "736a253a652860f684a382f5985198157d0e0308d798e8e959bc51dfa3604cb7",
    "unprobed_exclusion": "2675e28a013c10dbb99c58469de7181a3442f71bb10a38eab1be0a3e36bb2348",
    "denominator_floor_widened": "bdf6942ab0fba5f9f25b4f96408d2f082404d1ca816f68bf93b26c11e9511e96",
    "all_covered_perfect": "05292d6198339cb825339a7cdb1512bfb0feae2b55dba0cb7c96058c13ff4ffe",
    "mixed_types_structural_centrality": "3ea45d09bee0754fd059c22003422a912304fd27f2c7f9689849ca3c0c27bb1d",
    "empty_reference_graph": "6324dd3816cc7682b0d5d8f07d50597289e3770e8dac8a1d0b6c0a52ea811e22",
}

_CORPUS_NAMES = [name for name, _kwargs in inertness_corpus()]


def _case(name: str) -> dict[str, Any]:
    return dict(inertness_corpus())[name]


def _score_of(credits: dict[str, float], nodes: list, **kwargs: Any):
    """``compute_topic_score`` over an explicit per-node credit map."""
    return compute_topic_score(
        coverage={
            "per_step": {
                node.node_id: ("covered" if credits[node.node_id] >= 1.0 else "missing")
                for node in nodes
            },
            "procedure_scores": dict(credits),
        },
        reference_nodes=nodes,
        centrality=compute_centrality(KGGraph(nodes=nodes)),
        **kwargs,
    )


# --------------------------------------------------------------------------
# Inertness — the dark build proof.
# --------------------------------------------------------------------------
@pytest.mark.parametrize("name", _CORPUS_NAMES)
def test_misconceptions_none_is_byte_identical_to_today(name: str):
    """THE dark-build pin: the default call's whole serialized payload still
    hashes to what the pre-feature module produced, on every branch."""
    assert digest(compute_topic_score(**_case(name))) == PRE_FEATURE_DIGESTS[name]


@pytest.mark.parametrize("name", _CORPUS_NAMES)
def test_explicit_dark_defaults_match_the_implicit_call(name: str):
    """Passing the new keywords at their defaults is the SAME call, so a
    level-0/1/2 call site cannot diverge from the pre-feature one."""
    kwargs = _case(name)
    assert compute_topic_score(**kwargs, misconceptions=None, ceiling_active=False) == (
        compute_topic_score(**kwargs)
    )


def test_ceiling_active_without_findings_never_docks():
    """``ceiling_active=True`` alone is inert: with nothing corroborated there
    is no finding to attribute a dock to, so a clean attempt is never capped."""
    nodes = [equation("eq.one", "One")]
    baseline = _score_of({"eq.one": 1.0}, nodes)
    assert baseline.score == 100
    assert _score_of({"eq.one": 1.0}, nodes, ceiling_active=True) == baseline
    assert _score_of({"eq.one": 1.0}, nodes, misconceptions={}, ceiling_active=True) == baseline


# --------------------------------------------------------------------------
# P-1 / P-2 / P-3 — the three student-protective properties (§2.3 L4).
# --------------------------------------------------------------------------
def test_p1_ceiling_can_never_produce_a_d_or_an_f():
    """P-1: a ``min()`` cannot demote anyone into D or F. For every reachable
    raw score the ceilinged letter is D/F only when the raw letter already was,
    and above the ceiling the served letter is exactly B+."""
    for raw in range(0, 101):
        served = min(raw, CEILING_UNCORRECTED)
        if score_to_letter(served) in {"D", "F"}:
            assert score_to_letter(raw) in {"D", "F"}
        if raw > CEILING_UNCORRECTED:
            assert score_to_letter(served) == "B+"


def test_p1_holds_end_to_end_through_compute_topic_score():
    """The same property through the real scorer rather than the formula:
    sweeping one node's credit across the whole range with an uncorrected
    finding attached never lands a letter in a band the raw score wasn't in."""
    nodes = [equation("eq.one", "One"), equation("eq.two", "Two")]
    finding = {"eq.one": _Finding("eq.one", "reversed the sign")}
    for step in range(0, 101):
        credits = {"eq.one": step / 100, "eq.two": 1.0}
        raw = _score_of(credits, nodes)
        served = _score_of(credits, nodes, misconceptions=finding, ceiling_active=True)
        assert served.score == min(raw.score, CEILING_UNCORRECTED)
        if served.letter in {"D", "F"}:
            assert raw.letter in {"D", "F"}


def test_p2_ceiling_applied_once_not_repeated_subtraction():
    """P-2: one ``min()``, never a per-finding subtraction. Three uncorrected
    findings cap at the same 84 as one, the dock is ``raw - 84`` once, and the
    call is idempotent."""
    nodes = [equation("eq.one", "One"), equation("eq.two", "Two"), equation("eq.three", "Three")]
    credits = {"eq.one": 1.0, "eq.two": 1.0, "eq.three": 1.0}
    assert _score_of(credits, nodes).score == 100

    def _with(node_ids: tuple[str, ...]):
        return _score_of(
            credits,
            nodes,
            misconceptions={node_id: _Finding(node_id, "a") for node_id in node_ids},
            ceiling_active=True,
        )

    one = _with(("eq.one",))
    three = _with(("eq.one", "eq.two", "eq.three"))
    assert one.score == three.score == CEILING_UNCORRECTED
    assert one.misconception_dock == three.misconception_dock == 16.0
    assert three == _with(("eq.one", "eq.two", "eq.three"))


def test_p2_score_at_or_below_the_ceiling_is_never_touched():
    """The other half of P-2: the ceiling only binds above 84 — an attempt
    already at or under it keeps its exact score and takes a zero dock."""
    nodes = [equation("eq.one", "One"), equation("eq.two", "Two")]
    credits = {"eq.one": 0.6, "eq.two": 1.0}
    raw = _score_of(credits, nodes)
    assert raw.score <= CEILING_UNCORRECTED
    served = _score_of(
        credits, nodes, misconceptions={"eq.one": _Finding("eq.one", "a")}, ceiling_active=True
    )
    assert served.score == raw.score
    assert served.letter == raw.letter
    assert served.misconception_dock == 0.0
    assert served.topics[0].misconceptions[0].dock_points == 0.0


def test_p3_no_double_jeopardy_with_interaction5_aside_cap():
    """P-3: INTERACTION5's flat 0.5 aside cap and the ceiling can never stack.
    A Hoot-assisted node is capped at 0.5, strictly below the 0.6 credit gate
    S2' requires, so such a node can never carry a corroborated finding in the
    first place — the two levers are disjoint by arithmetic, not by policy."""
    nodes = [equation("eq.one", "One"), equation("eq.two", "Two")]
    capped, assisted = apply_aside_caps(
        {
            "per_step": {"eq.one": "covered", "eq.two": "covered"},
            "procedure_scores": {"eq.one": 1.0, "eq.two": 1.0},
            "hoot_assisted": {"eq.one": True, "eq.two": False},
        }
    )
    assert assisted == ("eq.one",)
    result = compute_topic_score(
        coverage=capped,
        reference_nodes=nodes,
        centrality=compute_centrality(KGGraph(nodes=nodes)),
    )
    assisted_topic = {topic.canonical_key: topic for topic in result.topics}["eq.one"]
    assert assisted_topic.credit == 0.5
    # THE disjointness: the capped credit is below the S2' corroboration gate,
    # which is numerically the same 0.6 this module already keys two other
    # decisions on. If that constant moves, this assertion moves with it.
    assert assisted_topic.credit < UNPROBED_CREDIT_KEEP_THRESHOLD == 0.6
    assert UNPROBED_CREDIT_KEEP_THRESHOLD == REFERENCE_TEXT_CREDIT_THRESHOLD


def test_dock_points_sum_exactly_to_misconception_dock():
    """Largest-remainder allocation: the per-finding lines sum to the attempt
    dock EXACTLY (integer points, so no float drift can reach a teacher) and the
    residual lands on the earliest finding in reference order."""
    nodes = [equation(f"eq.{index}", str(index)) for index in range(3)]
    credits = {node.node_id: 1.0 for node in nodes}
    result = _score_of(
        credits,
        nodes,
        misconceptions={node.node_id: _Finding(node.node_id, "a") for node in nodes},
        ceiling_active=True,
    )

    lines = [misc for topic in result.topics for misc in topic.misconceptions]
    assert sum(line.dock_points for line in lines) == result.misconception_dock == 16.0
    # 16 points over 3 findings -> 6/5/5, extra point first, deterministic.
    assert [line.dock_points for line in lines] == [6.0, 5.0, 5.0]


def test_resolved_findings_never_ceiling_and_never_carry_dock_points():
    """Decision D7: the ceiling is suppressed on resolution. A student who
    corrected the claim is reported, never capped."""
    nodes = [equation("eq.one", "One")]
    result = _score_of(
        {"eq.one": 1.0},
        nodes,
        misconceptions={"eq.one": _Finding("eq.one", "I was wrong", resolved=True)},
        ceiling_active=True,
    )
    assert result.score == 100
    assert result.misconception_dock == 0.0
    assert result.topics[0].misconceptions[0].resolved is True
    assert result.topics[0].misconceptions[0].dock_points == 0.0


def test_only_uncorrected_findings_share_the_dock():
    nodes = [equation("eq.one", "One"), equation("eq.two", "Two")]
    result = _score_of(
        {"eq.one": 1.0, "eq.two": 1.0},
        nodes,
        misconceptions={
            "eq.one": _Finding("eq.one", "fixed it", resolved=True),
            "eq.two": _Finding("eq.two", "still wrong"),
        },
        ceiling_active=True,
    )
    by_key = {topic.canonical_key: topic for topic in result.topics}
    assert by_key["eq.one"].misconceptions[0].dock_points == 0.0
    assert by_key["eq.two"].misconceptions[0].dock_points == 16.0
    assert result.misconception_dock == 16.0


def test_finding_for_an_unknown_node_is_ignored_and_never_ceilings():
    """A finding whose node is not part of this grade cannot be attributed, so
    it must never silently cap the attempt (fail-safe = miss)."""
    nodes = [equation("eq.one", "One")]
    result = _score_of(
        {"eq.one": 1.0},
        nodes,
        misconceptions={"ghost": _Finding("ghost", "a")},
        ceiling_active=True,
    )
    assert result.score == 100
    assert result.misconception_dock == 0.0
    assert all(topic.misconceptions == () for topic in result.topics)


# --------------------------------------------------------------------------
# Level 3 — containers populated, arithmetic untouched.
# --------------------------------------------------------------------------
def test_level3_shape_populates_misconceptions_without_moving_the_score():
    """LEVEL 3 (``ceiling_active=False``): ``topics[].misconceptions`` fills in
    with ``dock_points=0.0`` and the evidence span, while score, letter,
    coverage_component, misconception_dock and every topic's credit / status /
    weight stay exactly what the level-0 call produced."""
    nodes = [equation("eq.one", "One"), equation("eq.two", "Two")]
    credits = {"eq.one": 1.0, "eq.two": 1.0}
    baseline = _score_of(credits, nodes)
    level3 = _score_of(
        credits,
        nodes,
        misconceptions={"eq.one": _Finding("eq.one", "pressure rises with speed")},
    )

    assert level3.score == baseline.score
    assert level3.letter == baseline.letter
    assert level3.coverage_component == baseline.coverage_component
    assert level3.misconception_dock == baseline.misconception_dock == 0.0
    # The ONLY difference is the container.
    assert level3.topics[1] == baseline.topics[1]
    assert replace(level3.topics[0], misconceptions=()) == baseline.topics[0]
    (line,) = level3.topics[0].misconceptions
    assert line.canonical_key == "eq.one"
    assert line.resolved is False
    assert line.dock_points == 0.0
    assert line.evidence_span == "pressure rises with speed"


def test_level3_serializes_through_the_existing_serializer_unchanged():
    """``topic_score_serialize`` already carried both containers — this asserts
    it needed no change, which is why that file is untouched in this commit."""
    nodes = [equation("eq.one", "One")]
    result = _score_of(
        {"eq.one": 1.0},
        nodes,
        misconceptions={"eq.one": _Finding("eq.one", "quote", resolved=True)},
        ceiling_active=True,
    )
    payload = serialize_topic_score(result)
    assert payload["misconception_dock"] == 0.0
    assert payload["topics"][0]["misconceptions"] == [
        {
            "canonical_key": "eq.one",
            "resolved": True,
            "dock_points": 0.0,
            "evidence_span": "quote",
        }
    ]
