/*
 * DB-04: build the v1 target beside the frozen legacy public schema.
 *
 * This migration is intentionally DDL-only. It does not copy data and it does
 * not alter, rename, or drop any legacy public table.
 */

SET lock_timeout = '5s';
SET statement_timeout = '5min';

BEGIN;

DO $preconditions$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'app') THEN
        RAISE EXCEPTION 'DB-04 precondition failed: schema app already exists';
    END IF;
    IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'internal') THEN
        RAISE EXCEPTION 'DB-04 precondition failed: schema internal already exists';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'vector') THEN
        RAISE EXCEPTION 'DB-04 precondition failed: vector extension is not installed';
    END IF;
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'aita_search_spaces'
    ) THEN
        RAISE EXCEPTION 'DB-04 precondition failed: legacy public snapshot is missing';
    END IF;
END
$preconditions$;

CREATE SCHEMA app;
CREATE SCHEMA internal;
CREATE SCHEMA IF NOT EXISTS extensions;

-- pgvector objects are OID-linked, so legacy columns remain valid after the
-- extension namespace move. DB-03/DB-04 local rehearsal is the safety gate.
ALTER EXTENSION vector SET SCHEMA extensions;

DO $runtime_role$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_runtime') THEN
        CREATE ROLE app_runtime NOLOGIN NOBYPASSRLS;
    ELSIF EXISTS (
        SELECT 1 FROM pg_roles WHERE rolname = 'app_runtime' AND rolbypassrls
    ) THEN
        RAISE EXCEPTION 'DB-04 precondition failed: app_runtime must not BYPASSRLS';
    END IF;
END
$runtime_role$;

-- -------------------------------------------------------------------------
-- app: authenticated, tenant-bearing product records (21 tables)
-- -------------------------------------------------------------------------

CREATE TABLE app.courses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    slug text NOT NULL UNIQUE,
    subject_name text NOT NULL,
    current_week smallint NOT NULL DEFAULT 1,
    retrieval_weights jsonb NOT NULL DEFAULT '{}'::jsonb,
    retrieval_weight_min real NOT NULL DEFAULT 0,
    retrieval_weight_max real NOT NULL DEFAULT 1,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT courses__current_week__check CHECK (current_week BETWEEN 1 AND 16),
    CONSTRAINT courses__retrieval_weight_bounds__check CHECK (
        0 <= retrieval_weight_min
        AND retrieval_weight_min <= retrieval_weight_max
        AND retrieval_weight_max <= 1
    ),
    CONSTRAINT courses__retrieval_weights__object_check
        CHECK (jsonb_typeof(retrieval_weights) = 'object'),
    CONSTRAINT courses__metadata__object_check
        CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE TABLE app.course_memberships (
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    role text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, course_id),
    CONSTRAINT course_memberships__role__check CHECK (role IN ('student', 'teacher'))
);

CREATE TABLE app.course_invites (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    role text NOT NULL,
    created_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    is_active boolean NOT NULL DEFAULT true,
    max_uses integer,
    use_count integer NOT NULL DEFAULT 0,
    expires_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT course_invites__role__check CHECK (role IN ('student', 'teacher')),
    CONSTRAINT course_invites__max_uses__check CHECK (max_uses IS NULL OR max_uses > 0),
    CONSTRAINT course_invites__use_count__check CHECK (use_count >= 0)
);

CREATE UNIQUE INDEX course_invites__active_code__uidx
    ON app.course_invites (code) WHERE is_active;

CREATE TABLE app.documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    title text NOT NULL,
    document_type text NOT NULL DEFAULT 'EDUCATIONAL_FILE',
    material_kind text NOT NULL DEFAULT 'other',
    content text NOT NULL,
    source_markdown text,
    content_hash text NOT NULL UNIQUE,
    unique_identifier_hash text UNIQUE,
    embedding extensions.vector(3072),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    page_count integer,
    week integer,
    status text NOT NULL DEFAULT 'ready',
    failure_reason text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT documents__page_count__check CHECK (page_count IS NULL OR page_count >= 0),
    CONSTRAINT documents__week__check CHECK (week IS NULL OR week BETWEEN 0 AND 16),
    CONSTRAINT documents__status__check
        CHECK (status IN ('queued', 'processing', 'ready', 'failed')),
    CONSTRAINT documents__failure_reason__check
        CHECK (status = 'failed' OR failure_reason IS NULL),
    CONSTRAINT documents__metadata__object_check CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE TABLE app.uploads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    document_id bigint REFERENCES app.documents(id) ON DELETE SET NULL,
    week integer NOT NULL,
    kind text NOT NULL,
    title text NOT NULL,
    source_name text,
    page_count integer,
    is_latest boolean NOT NULL DEFAULT true,
    uploaded_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'ready',
    storage_key text,
    artifact_manifest jsonb NOT NULL DEFAULT '{}'::jsonb,
    ocr_provider text,
    ocr_details jsonb NOT NULL DEFAULT '{}'::jsonb,
    warning_count integer NOT NULL DEFAULT 0,
    error_message text,
    started_at timestamptz,
    completed_at timestamptz,
    attempt_count integer NOT NULL DEFAULT 0,
    uploaded_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uploads__week__check CHECK (week BETWEEN 0 AND 16),
    CONSTRAINT uploads__kind__check CHECK (kind IN ('notes', 'slides', 'textbook')),
    CONSTRAINT uploads__kind_week__check CHECK (
        (kind = 'textbook' AND week = 0)
        OR (kind IN ('notes', 'slides') AND week BETWEEN 1 AND 16)
    ),
    CONSTRAINT uploads__status__check
        CHECK (status IN ('queued', 'processing', 'ready', 'failed', 'superseded')),
    CONSTRAINT uploads__page_count__check CHECK (page_count IS NULL OR page_count >= 0),
    CONSTRAINT uploads__counts__check CHECK (warning_count >= 0 AND attempt_count >= 0),
    CONSTRAINT uploads__metadata__object_check CHECK (jsonb_typeof(metadata) = 'object'),
    CONSTRAINT uploads__artifact_manifest__object_check
        CHECK (jsonb_typeof(artifact_manifest) = 'object'),
    CONSTRAINT uploads__ocr_details__object_check CHECK (jsonb_typeof(ocr_details) = 'object')
);

CREATE UNIQUE INDEX uploads__latest_course_week_kind__uidx
    ON app.uploads (course_id, week, kind) WHERE is_latest;

CREATE TABLE app.chat_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id text NOT NULL UNIQUE,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    memory_summary text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chat_sessions__metadata__object_check CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE TABLE app.chat_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    chat_session_id bigint NOT NULL REFERENCES app.chat_sessions(id) ON DELETE CASCADE,
    turn_index integer NOT NULL,
    external_id text NOT NULL,
    role text NOT NULL,
    content text NOT NULL DEFAULT '',
    model text,
    tool_name text,
    tool_inputs jsonb,
    attachments jsonb NOT NULL DEFAULT '[]'::jsonb,
    citations jsonb NOT NULL DEFAULT '[]'::jsonb,
    keywords text[] NOT NULL DEFAULT '{}'::text[],
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (chat_session_id, external_id),
    UNIQUE (chat_session_id, turn_index),
    CONSTRAINT chat_messages__turn_index__check CHECK (turn_index >= 0),
    CONSTRAINT chat_messages__role__check CHECK (role IN ('user', 'assistant', 'tool', 'system')),
    CONSTRAINT chat_messages__tool_inputs__object_check
        CHECK (tool_inputs IS NULL OR jsonb_typeof(tool_inputs) = 'object'),
    CONSTRAINT chat_messages__attachments__array_check CHECK (jsonb_typeof(attachments) = 'array'),
    CONSTRAINT chat_messages__citations__array_check CHECK (jsonb_typeof(citations) = 'array')
);

CREATE TABLE app.tutoring_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    concept_id bigint,
    status text NOT NULL DEFAULT 'active',
    phase text NOT NULL DEFAULT 'INIT',
    current_problem_id bigint,
    pending_intent text,
    history_summary text,
    history_summary_up_to_turn integer,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    last_touched_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT tutoring_sessions__status__check CHECK (status IN ('active', 'paused', 'ended')),
    CONSTRAINT tutoring_sessions__phase__check
        CHECK (phase IN ('INIT', 'TEACHING', 'PROBLEM_REVEAL', 'SOLVING', 'REPORT', 'BETWEEN')),
    CONSTRAINT tutoring_sessions__summary_turn__check
        CHECK (history_summary_up_to_turn IS NULL OR history_summary_up_to_turn >= 0)
);

CREATE TABLE app.tutoring_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    session_id bigint NOT NULL REFERENCES app.tutoring_sessions(id) ON DELETE CASCADE,
    attempt_id bigint,
    role text NOT NULL,
    content text NOT NULL,
    turn_index integer NOT NULL,
    low_confidence_pattern boolean NOT NULL DEFAULT false,
    intent text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (session_id, turn_index),
    CONSTRAINT tutoring_messages__role__check CHECK (role IN ('student', 'apollo', 'system')),
    CONSTRAINT tutoring_messages__turn_index__check CHECK (turn_index >= 0),
    CONSTRAINT tutoring_messages__metadata__object_check CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE TABLE app.problem_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    session_id bigint NOT NULL REFERENCES app.tutoring_sessions(id) ON DELETE CASCADE,
    problem_id bigint NOT NULL,
    difficulty text NOT NULL,
    result text,
    solver_trace jsonb,
    diagnostic_report jsonb,
    learner_update_pending boolean NOT NULL DEFAULT false,
    learner_update_attempts integer NOT NULL DEFAULT 0,
    learner_update_failed_at timestamptz,
    learner_update_last_error text,
    learner_update_next_attempt_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT problem_attempts__difficulty__check CHECK (difficulty IN ('intro', 'standard', 'hard')),
    CONSTRAINT problem_attempts__result__check CHECK (
        result IS NULL OR result IN (
            'solved', 'stuck', 'skipped', 'returned_to_hoot', 'abandoned', 'graded'
        )
    ),
    CONSTRAINT problem_attempts__retry_count__check CHECK (learner_update_attempts >= 0),
    CONSTRAINT problem_attempts__solver_trace__object_check
        CHECK (solver_trace IS NULL OR jsonb_typeof(solver_trace) = 'object'),
    CONSTRAINT problem_attempts__diagnostic_report__object_check
        CHECK (diagnostic_report IS NULL OR jsonb_typeof(diagnostic_report) = 'object')
);

ALTER TABLE app.tutoring_messages
    ADD CONSTRAINT tutoring_messages__attempt_id__fkey
    FOREIGN KEY (attempt_id) REFERENCES app.problem_attempts(id) ON DELETE SET NULL;

CREATE TABLE app.student_progress (
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    xp_total integer NOT NULL DEFAULT 0,
    level integer NOT NULL DEFAULT 1,
    last_level_up_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, course_id),
    CONSTRAINT student_progress__xp_total__check CHECK (xp_total >= 0),
    CONSTRAINT student_progress__level__check CHECK (level >= 1)
);

CREATE TABLE app.subjects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    slug text NOT NULL,
    display_name text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (course_id, slug)
);

CREATE TABLE app.concepts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    subject_id bigint NOT NULL REFERENCES app.subjects(id) ON DELETE CASCADE,
    slug text NOT NULL,
    display_name text NOT NULL,
    description text NOT NULL DEFAULT '',
    canonical_symbols text[] NOT NULL DEFAULT '{}'::text[],
    symbol_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    normalization_map jsonb NOT NULL DEFAULT '{}'::jsonb,
    parser_prompt_template text NOT NULL DEFAULT '',
    solver_config jsonb NOT NULL DEFAULT '{}'::jsonb,
    parser_config jsonb NOT NULL DEFAULT '{}'::jsonb,
    forbidden_named_laws text[] NOT NULL DEFAULT '{}'::text[],
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (subject_id, slug),
    CONSTRAINT concepts__symbol_metadata__object_check CHECK (jsonb_typeof(symbol_metadata) = 'object'),
    CONSTRAINT concepts__normalization_map__object_check CHECK (jsonb_typeof(normalization_map) = 'object'),
    CONSTRAINT concepts__solver_config__object_check CHECK (jsonb_typeof(solver_config) = 'object'),
    CONSTRAINT concepts__parser_config__object_check CHECK (jsonb_typeof(parser_config) = 'object')
);

ALTER TABLE app.tutoring_sessions
    ADD CONSTRAINT tutoring_sessions__concept_id__fkey
    FOREIGN KEY (concept_id) REFERENCES app.concepts(id) ON DELETE RESTRICT;

CREATE TABLE app.problems (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    concept_id bigint NOT NULL REFERENCES app.concepts(id) ON DELETE CASCADE,
    problem_code text NOT NULL,
    difficulty text NOT NULL,
    problem_text text NOT NULL,
    given_values jsonb NOT NULL DEFAULT '{}'::jsonb,
    target_unknown text NOT NULL DEFAULT '',
    reference_solution jsonb NOT NULL,
    payload_extra jsonb NOT NULL DEFAULT '{}'::jsonb,
    tier smallint NOT NULL DEFAULT 1,
    solution_source text,
    provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
    quarantined_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (concept_id, problem_code),
    CONSTRAINT problems__difficulty__check CHECK (difficulty IN ('intro', 'standard', 'hard')),
    CONSTRAINT problems__tier__check CHECK (tier IN (1, 2)),
    CONSTRAINT problems__solution_source__check
        CHECK (solution_source IS NULL OR solution_source IN ('extracted', 'generated', 'authored', 'llm_paired')),
    CONSTRAINT problems__given_values__object_check CHECK (jsonb_typeof(given_values) = 'object'),
    CONSTRAINT problems__reference_solution__object_check CHECK (jsonb_typeof(reference_solution) = 'object'),
    CONSTRAINT problems__payload_extra__object_check CHECK (jsonb_typeof(payload_extra) = 'object'),
    CONSTRAINT problems__provenance__object_check CHECK (jsonb_typeof(provenance) = 'object')
);

ALTER TABLE app.tutoring_sessions
    ADD CONSTRAINT tutoring_sessions__current_problem_id__fkey
    FOREIGN KEY (current_problem_id) REFERENCES app.problems(id) ON DELETE SET NULL;

ALTER TABLE app.problem_attempts
    ADD CONSTRAINT problem_attempts__problem_id__fkey
    FOREIGN KEY (problem_id) REFERENCES app.problems(id) ON DELETE RESTRICT;

CREATE TABLE app.authored_sets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    set_index integer NOT NULL,
    problem_document_id bigint REFERENCES app.documents(id) ON DELETE RESTRICT,
    solution_document_id bigint REFERENCES app.documents(id) ON DELETE RESTRICT,
    status text NOT NULL DEFAULT 'pending',
    result_summary jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (course_id, set_index),
    CONSTRAINT authored_sets__set_index__check CHECK (set_index >= 0),
    CONSTRAINT authored_sets__status__check
        CHECK (status IN ('pending', 'indexing', 'provisioning', 'done', 'failed')),
    CONSTRAINT authored_sets__result_summary__object_check CHECK (jsonb_typeof(result_summary) = 'object')
);

CREATE TABLE app.question_opportunities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    session_id bigint NOT NULL REFERENCES app.tutoring_sessions(id) ON DELETE CASCADE,
    attempt_id bigint NOT NULL REFERENCES app.problem_attempts(id) ON DELETE CASCADE,
    reference_node_id text NOT NULL,
    state text NOT NULL DEFAULT 'asked_waiting',
    question text NOT NULL DEFAULT '',
    asked_turn integer,
    answered_turn integer,
    evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
    student_declined boolean NOT NULL DEFAULT false,
    times_asked integer NOT NULL DEFAULT 0,
    last_asked_turn integer,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (attempt_id, reference_node_id),
    CONSTRAINT question_opportunities__turns__check CHECK (
        (asked_turn IS NULL OR asked_turn >= 0)
        AND (answered_turn IS NULL OR answered_turn >= 0)
        AND (last_asked_turn IS NULL OR last_asked_turn >= 0)
    ),
    CONSTRAINT question_opportunities__times_asked__check CHECK (times_asked >= 0),
    CONSTRAINT question_opportunities__evidence__array_check CHECK (jsonb_typeof(evidence) = 'array')
);

CREATE TABLE app.learner_entities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    concept_id bigint NOT NULL REFERENCES app.concepts(id) ON DELETE CASCADE,
    canonical_key text NOT NULL,
    kind text NOT NULL,
    display_name text NOT NULL,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    aliases text[] NOT NULL DEFAULT '{}'::text[],
    scope_summary text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (concept_id, canonical_key),
    CONSTRAINT learner_entities__kind__check
        CHECK (kind IN ('concept', 'equation', 'condition', 'definition', 'procedure', 'variable')),
    CONSTRAINT learner_entities__payload__object_check CHECK (jsonb_typeof(payload) = 'object')
);

CREATE TABLE app.learner_state (
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    entity_id bigint NOT NULL REFERENCES app.learner_entities(id) ON DELETE CASCADE,
    belief real[] NOT NULL,
    mastery real NOT NULL,
    confidence real NOT NULL,
    evidence_count integer NOT NULL DEFAULT 0,
    last_evidence_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, course_id, entity_id),
    CONSTRAINT learner_state__belief__check CHECK (
        array_length(belief, 1) = 3
        AND belief[1] BETWEEN 0 AND 1
        AND belief[2] BETWEEN 0 AND 1
        AND belief[3] BETWEEN 0 AND 1
        AND abs((belief[1] + belief[2] + belief[3]) - 1.0) <= 0.001
    ),
    CONSTRAINT learner_state__mastery__check CHECK (mastery BETWEEN 0 AND 1),
    CONSTRAINT learner_state__confidence__check CHECK (confidence BETWEEN 0 AND 1),
    CONSTRAINT learner_state__evidence_count__check CHECK (evidence_count >= 0)
);

CREATE TABLE app.mastery_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    entity_id bigint NOT NULL REFERENCES app.learner_entities(id) ON DELETE CASCADE,
    attempt_id bigint REFERENCES app.problem_attempts(id) ON DELETE SET NULL,
    concept_problem_id bigint REFERENCES app.problems(id) ON DELETE SET NULL,
    event_kind text NOT NULL,
    score real,
    parser_confidence real,
    grader_confidence real,
    negotiation_move text,
    reference_step_id text,
    prior_belief real[] NOT NULL,
    posterior_belief real[] NOT NULL,
    mastery_after real NOT NULL,
    dt_days_since_last real,
    evidence_node_ids text[] NOT NULL DEFAULT '{}'::text[],
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT mastery_events__attempt_entity_kind__uniq
        UNIQUE NULLS NOT DISTINCT (attempt_id, entity_id, event_kind),
    CONSTRAINT mastery_events__score__check CHECK (score IS NULL OR score BETWEEN 0 AND 1),
    CONSTRAINT mastery_events__parser_confidence__check
        CHECK (parser_confidence IS NULL OR parser_confidence BETWEEN 0 AND 1),
    CONSTRAINT mastery_events__grader_confidence__check
        CHECK (grader_confidence IS NULL OR grader_confidence BETWEEN 0 AND 1),
    CONSTRAINT mastery_events__negotiation_move__check
        CHECK (negotiation_move IS NULL OR negotiation_move IN ('challenge', 'paraphrase', 'skip')),
    CONSTRAINT mastery_events__prior_belief__check CHECK (array_length(prior_belief, 1) = 3),
    CONSTRAINT mastery_events__posterior_belief__check CHECK (array_length(posterior_belief, 1) = 3),
    CONSTRAINT mastery_events__mastery_after__check CHECK (mastery_after BETWEEN 0 AND 1),
    CONSTRAINT mastery_events__dt_days__check CHECK (dt_days_since_last IS NULL OR dt_days_since_last >= 0)
);

CREATE TABLE app.learner_negotiations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    attempt_id bigint NOT NULL REFERENCES app.problem_attempts(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    entry_id text NOT NULL,
    actor text NOT NULL,
    move text NOT NULL,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT learner_negotiations__actor__check CHECK (actor IN ('student', 'parser', 'system')),
    CONSTRAINT learner_negotiations__move__check CHECK (move IN ('challenge', 'paraphrase', 'skip')),
    CONSTRAINT learner_negotiations__payload__object_check CHECK (jsonb_typeof(payload) = 'object')
);

CREATE TABLE app.ai_usage_reports (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    chat_id text NOT NULL REFERENCES app.chat_sessions(external_id) ON DELETE CASCADE,
    style text,
    length text,
    markdown text,
    jsonld jsonb,
    model_fingerprint text,
    tool_calls jsonb,
    prompt_hashes text[] NOT NULL DEFAULT '{}'::text[],
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ai_usage_reports__jsonld__object_check
        CHECK (jsonld IS NULL OR jsonb_typeof(jsonld) = 'object'),
    CONSTRAINT ai_usage_reports__tool_calls__array_check
        CHECK (tool_calls IS NULL OR jsonb_typeof(tool_calls) = 'array')
);

-- -------------------------------------------------------------------------
-- internal: service-only queues, retrieval, telemetry, and grading (12 tables)
-- -------------------------------------------------------------------------

CREATE TABLE internal.document_chunks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    document_id bigint NOT NULL REFERENCES app.documents(id) ON DELETE CASCADE,
    content text NOT NULL,
    embedding extensions.vector(3072),
    page_number integer,
    section_path text,
    chunk_type text NOT NULL DEFAULT 'body',
    figure_id text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT document_chunks__page_number__check CHECK (page_number IS NULL OR page_number >= 0)
);

CREATE TABLE internal.upload_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    upload_id bigint NOT NULL REFERENCES app.uploads(id) ON DELETE CASCADE,
    state text NOT NULL DEFAULT 'queued',
    lease_owner text,
    lease_expires_at timestamptz,
    attempt_count integer NOT NULL DEFAULT 0,
    last_error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT upload_jobs__state__check CHECK (state IN ('queued', 'leased', 'processing', 'completed', 'failed')),
    CONSTRAINT upload_jobs__attempt_count__check CHECK (attempt_count >= 0)
);

CREATE TABLE internal.chat_session_snippets (
    chat_session_id bigint NOT NULL REFERENCES app.chat_sessions(id) ON DELETE CASCADE,
    chunk_id bigint NOT NULL REFERENCES internal.document_chunks(id) ON DELETE CASCADE,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    original_score real NOT NULL,
    first_seen_turn integer NOT NULL,
    last_used_turn integer NOT NULL,
    snippet_payload jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (chat_session_id, chunk_id),
    CONSTRAINT chat_session_snippets__turns__check
        CHECK (first_seen_turn >= 0 AND last_used_turn >= first_seen_turn),
    CONSTRAINT chat_session_snippets__payload__object_check CHECK (jsonb_typeof(snippet_payload) = 'object')
);

CREATE TABLE internal.chat_routing_decisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    chat_session_id bigint NOT NULL REFERENCES app.chat_sessions(id) ON DELETE CASCADE,
    turn_id text NOT NULL,
    query text NOT NULL,
    stage1_top1 real,
    stage1_margin real,
    stage1_route text,
    stage2_invoked boolean NOT NULL DEFAULT false,
    stage2_route text,
    stage2_confidence real,
    retrieval_mode text NOT NULL,
    retrieval_top_score real,
    final_route text NOT NULL,
    was_clarified boolean NOT NULL DEFAULT false,
    clarify_cause text,
    latency_router_ms integer,
    latency_retrieval_ms integer,
    latency_answer_ms integer,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chat_routing_decisions__latencies__check CHECK (
        (latency_router_ms IS NULL OR latency_router_ms >= 0)
        AND (latency_retrieval_ms IS NULL OR latency_retrieval_ms >= 0)
        AND (latency_answer_ms IS NULL OR latency_answer_ms >= 0)
    )
);

CREATE TABLE internal.content_ingest_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    document_id bigint REFERENCES app.documents(id) ON DELETE SET NULL,
    content_hash text,
    status text NOT NULL DEFAULT 'queued',
    n_questions_scraped integer NOT NULL DEFAULT 0,
    n_promoted integer NOT NULL DEFAULT 0,
    n_rejected integer NOT NULL DEFAULT 0,
    n_dedup_merged integer NOT NULL DEFAULT 0,
    n_pages integer NOT NULL DEFAULT 0,
    llm_calls integer NOT NULL DEFAULT 0,
    llm_tokens_in bigint NOT NULL DEFAULT 0,
    llm_tokens_out bigint NOT NULL DEFAULT 0,
    llm_cost_usd numeric(12,6) NOT NULL DEFAULT 0,
    dedup_total_candidates integer NOT NULL DEFAULT 0,
    dedup_exact_merges integer NOT NULL DEFAULT 0,
    dedup_embedding_merges integer NOT NULL DEFAULT 0,
    dedup_embedding_distinct integer NOT NULL DEFAULT 0,
    dedup_embedding_merge_ratio real NOT NULL DEFAULT 0,
    dedup_details jsonb NOT NULL DEFAULT '{}'::jsonb,
    started_at timestamptz,
    finished_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT content_ingest_runs__status__check
        CHECK (status IN ('queued', 'running', 'succeeded', 'failed')),
    CONSTRAINT content_ingest_runs__counts__check CHECK (
        n_questions_scraped >= 0 AND n_promoted >= 0 AND n_rejected >= 0
        AND n_dedup_merged >= 0 AND n_pages >= 0 AND llm_calls >= 0
        AND llm_tokens_in >= 0 AND llm_tokens_out >= 0 AND llm_cost_usd >= 0
        AND dedup_total_candidates >= 0 AND dedup_exact_merges >= 0
        AND dedup_embedding_merges >= 0 AND dedup_embedding_distinct >= 0
    ),
    CONSTRAINT content_ingest_runs__dedup_ratio__check
        CHECK (dedup_embedding_merge_ratio BETWEEN 0 AND 1),
    CONSTRAINT content_ingest_runs__dedup_details__object_check
        CHECK (jsonb_typeof(dedup_details) = 'object')
);

CREATE TABLE internal.content_ingest_errors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    ingest_run_id bigint REFERENCES internal.content_ingest_runs(id) ON DELETE CASCADE,
    stage text NOT NULL,
    error_class text NOT NULL,
    context jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT content_ingest_errors__context__object_check CHECK (jsonb_typeof(context) = 'object')
);

CREATE TABLE internal.ingest_page_evidence (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    ingest_run_id bigint NOT NULL REFERENCES internal.content_ingest_runs(id) ON DELETE CASCADE,
    document_id bigint REFERENCES app.documents(id) ON DELETE SET NULL,
    role text NOT NULL,
    page_number integer,
    ocr_text text NOT NULL DEFAULT '',
    ocr_confidence real,
    extraction_mode text,
    verify_path_fired boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ingest_page_evidence__role__check CHECK (role IN ('problem', 'solution')),
    CONSTRAINT ingest_page_evidence__page_number__check CHECK (page_number IS NULL OR page_number >= 0),
    CONSTRAINT ingest_page_evidence__ocr_confidence__check
        CHECK (ocr_confidence IS NULL OR ocr_confidence BETWEEN 0 AND 1)
);

CREATE TABLE internal.dedup_decisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    ingest_run_id bigint REFERENCES internal.content_ingest_runs(id) ON DELETE CASCADE,
    concept_id bigint REFERENCES app.concepts(id) ON DELETE SET NULL,
    matched_entity_id bigint REFERENCES app.learner_entities(id) ON DELETE SET NULL,
    candidate_key text NOT NULL,
    method text NOT NULL,
    similarity real,
    verdict text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT dedup_decisions__method__check CHECK (method IN ('slug', 'embedding', 'llm_judge')),
    CONSTRAINT dedup_decisions__similarity__check CHECK (similarity IS NULL OR similarity BETWEEN 0 AND 1),
    CONSTRAINT dedup_decisions__verdict__check CHECK (verdict IN ('merged', 'distinct'))
);

CREATE TABLE internal.entity_prerequisites (
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    from_entity_id bigint NOT NULL REFERENCES app.learner_entities(id) ON DELETE CASCADE,
    to_entity_id bigint NOT NULL REFERENCES app.learner_entities(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (from_entity_id, to_entity_id),
    CONSTRAINT entity_prerequisites__not_self__check CHECK (from_entity_id <> to_entity_id)
);

CREATE TABLE internal.content_generation_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    concept_id bigint NOT NULL REFERENCES app.concepts(id) ON DELETE CASCADE,
    status text NOT NULL DEFAULT 'pending',
    result_summary jsonb NOT NULL DEFAULT '{}'::jsonb,
    ingest_run_id bigint REFERENCES internal.content_ingest_runs(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT content_generation_runs__status__check
        CHECK (status IN ('pending', 'running', 'succeeded', 'failed')),
    CONSTRAINT content_generation_runs__result_summary__object_check
        CHECK (jsonb_typeof(result_summary) = 'object')
);

CREATE TABLE internal.grading_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    attempt_id bigint NOT NULL REFERENCES app.problem_attempts(id) ON DELETE CASCADE,
    concept_id bigint REFERENCES app.concepts(id) ON DELETE SET NULL,
    problem_id bigint NOT NULL REFERENCES app.problems(id) ON DELETE RESTRICT,
    role text NOT NULL,
    grader_used text NOT NULL,
    grader_version text NOT NULL,
    reference_graph_hash text,
    weights_version text,
    status text NOT NULL DEFAULT 'final',
    grading_latency_ms integer,
    composite_score real,
    coverage_score real,
    soundness_score real,
    bisimilarity_score real,
    node_coverage_score real,
    edge_coverage_score real,
    scoping_score real,
    usage_score real,
    procedure_order_score real,
    dependency_score real,
    contradiction_score real,
    normalization_confidence real,
    soundness_applicable boolean,
    abstained boolean NOT NULL DEFAULT false,
    version_details jsonb NOT NULL DEFAULT '{}'::jsonb,
    node_ledger jsonb NOT NULL DEFAULT '[]'::jsonb,
    edge_ledger jsonb NOT NULL DEFAULT '[]'::jsonb,
    score_details jsonb NOT NULL DEFAULT '{}'::jsonb,
    abstention_details jsonb,
    grader_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    -- Evidence Graph v2 seam: nullable until the separately reviewed v2 writer lands.
    transcript_freeze_hash text,
    reference_graph_version text,
    evidence_adjudicator_version text,
    verifier_versions jsonb,
    verifier_versions_hash text,
    inference_config_hash text,
    band_policy_version text,
    dimensions jsonb,
    applied_rule_ids jsonb,
    robustness_result jsonb,
    clarification_history_ref jsonb,
    band text,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (attempt_id, role, grader_version),
    CONSTRAINT grading_runs__role__check CHECK (role IN ('canonical', 'pair', 'shadow')),
    CONSTRAINT grading_runs__grader_used__check
        CHECK (grader_used IN ('graph', 'llm_fallback', 'llm_transcript', 'evidence_graph_v2')),
    CONSTRAINT grading_runs__status__check CHECK (
        status IN ('collecting', 'awaiting_clarification', 'inferring', 'grading_pending',
                   'provisional', 'final', 'manual_review', 'shadow')
    ),
    CONSTRAINT grading_runs__latency__check CHECK (grading_latency_ms IS NULL OR grading_latency_ms >= 0),
    CONSTRAINT grading_runs__scores__check CHECK (
        (composite_score IS NULL OR composite_score BETWEEN 0 AND 1)
        AND (coverage_score IS NULL OR coverage_score BETWEEN 0 AND 1)
        AND (soundness_score IS NULL OR soundness_score BETWEEN 0 AND 1)
        AND (bisimilarity_score IS NULL OR bisimilarity_score BETWEEN 0 AND 1)
        AND (node_coverage_score IS NULL OR node_coverage_score BETWEEN 0 AND 1)
        AND (edge_coverage_score IS NULL OR edge_coverage_score BETWEEN 0 AND 1)
        AND (scoping_score IS NULL OR scoping_score BETWEEN 0 AND 1)
        AND (usage_score IS NULL OR usage_score BETWEEN 0 AND 1)
        AND (procedure_order_score IS NULL OR procedure_order_score BETWEEN 0 AND 1)
        AND (dependency_score IS NULL OR dependency_score BETWEEN 0 AND 1)
        AND (contradiction_score IS NULL OR contradiction_score BETWEEN 0 AND 1)
        AND (normalization_confidence IS NULL OR normalization_confidence BETWEEN 0 AND 1)
    ),
    CONSTRAINT grading_runs__version_details__object_check CHECK (jsonb_typeof(version_details) = 'object'),
    CONSTRAINT grading_runs__node_ledger__array_check CHECK (jsonb_typeof(node_ledger) = 'array'),
    CONSTRAINT grading_runs__edge_ledger__array_check CHECK (jsonb_typeof(edge_ledger) = 'array'),
    CONSTRAINT grading_runs__score_details__object_check CHECK (jsonb_typeof(score_details) = 'object'),
    CONSTRAINT grading_runs__abstention_details__object_check
        CHECK (abstention_details IS NULL OR jsonb_typeof(abstention_details) = 'object'),
    CONSTRAINT grading_runs__grader_payload__object_check CHECK (jsonb_typeof(grader_payload) = 'object'),
    CONSTRAINT grading_runs__verifier_versions__object_check
        CHECK (verifier_versions IS NULL OR jsonb_typeof(verifier_versions) = 'object'),
    CONSTRAINT grading_runs__dimensions__object_check
        CHECK (dimensions IS NULL OR jsonb_typeof(dimensions) = 'object'),
    CONSTRAINT grading_runs__applied_rule_ids__array_check
        CHECK (applied_rule_ids IS NULL OR jsonb_typeof(applied_rule_ids) = 'array'),
    CONSTRAINT grading_runs__robustness_result__object_check
        CHECK (robustness_result IS NULL OR jsonb_typeof(robustness_result) = 'object'),
    CONSTRAINT grading_runs__clarification_history_ref__object_check
        CHECK (clarification_history_ref IS NULL OR jsonb_typeof(clarification_history_ref) = 'object')
);

CREATE TABLE internal.grading_findings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
    run_id bigint NOT NULL REFERENCES internal.grading_runs(id) ON DELETE CASCADE,
    entity_id bigint REFERENCES app.learner_entities(id) ON DELETE SET NULL,
    finding_kind text NOT NULL,
    score real,
    confidence real,
    student_node_ids text[] NOT NULL DEFAULT '{}'::text[],
    reference_node_ids text[] NOT NULL DEFAULT '{}'::text[],
    student_edge_ids text[] NOT NULL DEFAULT '{}'::text[],
    reference_edge_ids text[] NOT NULL DEFAULT '{}'::text[],
    evidence_spans jsonb NOT NULL DEFAULT '[]'::jsonb,
    message text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT grading_findings__score__check CHECK (score IS NULL OR score BETWEEN 0 AND 1),
    CONSTRAINT grading_findings__confidence__check CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1),
    CONSTRAINT grading_findings__evidence_spans__array_check CHECK (jsonb_typeof(evidence_spans) = 'array')
);

-- -------------------------------------------------------------------------
-- Minimal index allowlist: PK/UNIQUE indexes above plus FK, RLS, queue,
-- retrieval, curriculum, and history paths named per the v1 convention.
-- -------------------------------------------------------------------------

CREATE INDEX course_memberships__course_role_user__idx
    ON app.course_memberships (course_id, role, user_id);
CREATE INDEX course_invites__created_by_course__idx
    ON app.course_invites (created_by, course_id);
CREATE INDEX documents__course_created__idx ON app.documents (course_id, created_at);
CREATE INDEX uploads__document_id__idx ON app.uploads (document_id);
CREATE INDEX uploads__uploaded_by_course__idx ON app.uploads (uploaded_by, course_id);
CREATE INDEX chat_sessions__user_course__idx ON app.chat_sessions (user_id, course_id);
CREATE INDEX chat_messages__course_session__idx ON app.chat_messages (course_id, chat_session_id);
CREATE INDEX tutoring_sessions__user_course__idx ON app.tutoring_sessions (user_id, course_id);
CREATE INDEX tutoring_sessions__current_problem_id__idx ON app.tutoring_sessions (current_problem_id);
CREATE UNIQUE INDEX tutoring_sessions__active_user_course__uidx
    ON app.tutoring_sessions (user_id, course_id) WHERE status = 'active';
CREATE INDEX tutoring_messages__course_session__idx ON app.tutoring_messages (course_id, session_id);
CREATE INDEX tutoring_messages__attempt_id__idx ON app.tutoring_messages (attempt_id);
CREATE INDEX problem_attempts__user_course__idx ON app.problem_attempts (user_id, course_id);
CREATE INDEX problem_attempts__session_created__idx ON app.problem_attempts (session_id, created_at);
CREATE INDEX problem_attempts__problem_id__idx ON app.problem_attempts (problem_id);
CREATE INDEX problem_attempts__learner_retry__idx
    ON app.problem_attempts (learner_update_next_attempt_at)
    WHERE learner_update_pending;
CREATE INDEX subjects__course_slug__idx ON app.subjects (course_id, slug);
CREATE INDEX concepts__course_subject__idx ON app.concepts (course_id, subject_id);
CREATE INDEX problems__course_quarantined__idx ON app.problems (course_id, quarantined_at);
CREATE INDEX problems__concept_tier_difficulty__idx ON app.problems (concept_id, tier, difficulty);
CREATE INDEX authored_sets__problem_document__idx ON app.authored_sets (problem_document_id);
CREATE INDEX authored_sets__solution_document__idx ON app.authored_sets (solution_document_id);
CREATE INDEX question_opportunities__course_session__idx
    ON app.question_opportunities (course_id, session_id);
CREATE INDEX question_opportunities__session_id__idx ON app.question_opportunities (session_id);
CREATE INDEX learner_entities__course_concept__idx ON app.learner_entities (course_id, concept_id);
CREATE INDEX learner_state__entity_id__idx ON app.learner_state (entity_id);
CREATE INDEX mastery_events__course_entity__idx ON app.mastery_events (course_id, entity_id);
CREATE INDEX mastery_events__user_entity_created__idx
    ON app.mastery_events (user_id, entity_id, created_at);
CREATE INDEX mastery_events__attempt_id__idx ON app.mastery_events (attempt_id);
CREATE INDEX mastery_events__concept_problem_id__idx ON app.mastery_events (concept_problem_id);
CREATE INDEX learner_negotiations__course_attempt__idx ON app.learner_negotiations (course_id, attempt_id);
CREATE INDEX learner_negotiations__user_course__idx ON app.learner_negotiations (user_id, course_id);
CREATE INDEX ai_usage_reports__user_course__idx ON app.ai_usage_reports (user_id, course_id);
CREATE INDEX ai_usage_reports__chat_id__idx ON app.ai_usage_reports (chat_id);

CREATE INDEX document_chunks__course_document__idx
    ON internal.document_chunks (course_id, document_id);
CREATE INDEX document_chunks__document_page__idx
    ON internal.document_chunks (document_id, page_number);
CREATE INDEX document_chunks__content_fts__idx
    ON internal.document_chunks USING gin (to_tsvector('english', content));
CREATE INDEX document_chunks__embedding_halfvec_hnsw__idx
    ON internal.document_chunks USING hnsw
    ((embedding::extensions.halfvec(3072)) extensions.halfvec_cosine_ops);
CREATE INDEX upload_jobs__course_upload__idx ON internal.upload_jobs (course_id, upload_id);
CREATE INDEX upload_jobs__dequeue__idx
    ON internal.upload_jobs (state, lease_expires_at, created_at);
CREATE INDEX chat_session_snippets__course_session__idx
    ON internal.chat_session_snippets (course_id, chat_session_id);
CREATE INDEX chat_session_snippets__chunk_id__idx
    ON internal.chat_session_snippets (chunk_id);
CREATE INDEX chat_routing_decisions__course_session__idx
    ON internal.chat_routing_decisions (course_id, chat_session_id);
CREATE INDEX content_ingest_runs__course_document__idx
    ON internal.content_ingest_runs (course_id, document_id);
CREATE INDEX content_ingest_errors__course_run__idx
    ON internal.content_ingest_errors (course_id, ingest_run_id);
CREATE INDEX ingest_page_evidence__course_run__idx
    ON internal.ingest_page_evidence (course_id, ingest_run_id);
CREATE INDEX ingest_page_evidence__document_id__idx
    ON internal.ingest_page_evidence (document_id);
CREATE INDEX dedup_decisions__course_run__idx
    ON internal.dedup_decisions (course_id, ingest_run_id);
CREATE INDEX dedup_decisions__concept_id__idx ON internal.dedup_decisions (concept_id);
CREATE INDEX dedup_decisions__matched_entity_id__idx
    ON internal.dedup_decisions (matched_entity_id);
CREATE INDEX entity_prerequisites__course_from__idx
    ON internal.entity_prerequisites (course_id, from_entity_id);
CREATE INDEX entity_prerequisites__to_entity_id__idx
    ON internal.entity_prerequisites (to_entity_id);
CREATE INDEX content_generation_runs__course_concept__idx
    ON internal.content_generation_runs (course_id, concept_id);
CREATE INDEX content_generation_runs__ingest_run_id__idx
    ON internal.content_generation_runs (ingest_run_id);
CREATE INDEX grading_runs__course_user__idx ON internal.grading_runs (course_id, user_id);
CREATE INDEX grading_runs__user_course__idx ON internal.grading_runs (user_id, course_id);
CREATE INDEX grading_runs__attempt_created__idx ON internal.grading_runs (attempt_id, created_at);
CREATE INDEX grading_runs__concept_id__idx ON internal.grading_runs (concept_id);
CREATE INDEX grading_runs__problem_id__idx ON internal.grading_runs (problem_id);
CREATE INDEX grading_findings__course_run__idx ON internal.grading_findings (course_id, run_id);
CREATE INDEX grading_findings__entity_id__idx ON internal.grading_findings (entity_id);

-- Retrieval functions are built against the new store but remain internal and
-- ungranted until the activation migration switches the backend callers.
CREATE FUNCTION internal.fetch_items(
    p_chunk_ids bigint[],
    p_document_ids bigint[]
)
RETURNS SETOF internal.document_chunks
LANGUAGE sql
STABLE
SET search_path = ''
AS $function$
    SELECT chunks.*
    FROM internal.document_chunks AS chunks
    WHERE chunks.id = ANY (p_chunk_ids)
      AND chunks.document_id = ANY (p_document_ids)
$function$;

CREATE FUNCTION internal.fts_count(
    query_text text,
    p_document_ids bigint[]
)
RETURNS integer
LANGUAGE sql
STABLE
SET search_path = ''
AS $function$
    SELECT count(*)::integer
    FROM internal.document_chunks AS chunks
    WHERE chunks.document_id = ANY (p_document_ids)
      AND pg_catalog.to_tsvector('english', chunks.content)
          @@ pg_catalog.websearch_to_tsquery('english', query_text)
$function$;

CREATE FUNCTION internal.hybrid_search(
    query_text text,
    query_embedding extensions.vector(3072),
    p_document_ids bigint[],
    match_count integer,
    rrf_k integer DEFAULT 60
)
RETURNS TABLE (
    chunk_id bigint,
    document_id bigint,
    semantic_score double precision,
    lexical_score double precision,
    semantic_rank integer,
    lexical_rank integer
)
LANGUAGE sql
STABLE
SET search_path = ''
AS $function$
    WITH sem AS (
        SELECT
            chunks.id,
            chunks.document_id,
            1.0 - (
                chunks.embedding::extensions.halfvec(3072)
                OPERATOR(extensions.<=>)
                query_embedding::extensions.halfvec(3072)
            ) AS score,
            row_number() OVER (
                ORDER BY
                    chunks.embedding::extensions.halfvec(3072)
                    OPERATOR(extensions.<=>)
                    query_embedding::extensions.halfvec(3072)
            )::integer AS rnk
        FROM internal.document_chunks AS chunks
        ORDER BY
            chunks.embedding::extensions.halfvec(3072)
            OPERATOR(extensions.<=>)
            query_embedding::extensions.halfvec(3072)
        LIMIT match_count * 10
    ),
    sem_filtered AS (
        SELECT * FROM sem
        WHERE document_id = ANY (p_document_ids)
        LIMIT match_count * 2
    ),
    lex AS (
        SELECT
            chunks.id,
            chunks.document_id,
            pg_catalog.ts_rank_cd(
                pg_catalog.to_tsvector('english', chunks.content),
                pg_catalog.websearch_to_tsquery('english', query_text)
            ) AS score,
            row_number() OVER (
                ORDER BY pg_catalog.ts_rank_cd(
                    pg_catalog.to_tsvector('english', chunks.content),
                    pg_catalog.websearch_to_tsquery('english', query_text)
                ) DESC
            )::integer AS rnk
        FROM internal.document_chunks AS chunks
        WHERE chunks.document_id = ANY (p_document_ids)
          AND pg_catalog.to_tsvector('english', chunks.content)
              @@ pg_catalog.websearch_to_tsquery('english', query_text)
        LIMIT match_count * 2
    )
    SELECT
        coalesce(sem_filtered.id, lex.id),
        coalesce(sem_filtered.document_id, lex.document_id),
        coalesce(sem_filtered.score, 0.0)::double precision,
        coalesce(lex.score, 0.0)::double precision,
        coalesce(sem_filtered.rnk, match_count * 2 + 1)::integer,
        coalesce(lex.rnk, match_count * 2 + 1)::integer
    FROM sem_filtered
    FULL OUTER JOIN lex
      ON sem_filtered.id = lex.id
     AND sem_filtered.document_id = lex.document_id
    ORDER BY (
        1.0 / (rrf_k + coalesce(sem_filtered.rnk, match_count * 2 + 1))
        + 1.0 / (rrf_k + coalesce(lex.rnk, match_count * 2 + 1))
    ) DESC
    LIMIT match_count
$function$;

REVOKE ALL ON FUNCTION internal.fetch_items(bigint[], bigint[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION internal.fts_count(text, bigint[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION internal.hybrid_search(
    text, extensions.vector, bigint[], integer, integer
) FROM PUBLIC;

-- -------------------------------------------------------------------------
-- RLS helper and authenticated policies
-- -------------------------------------------------------------------------

CREATE FUNCTION internal.has_course_role(p_course_id bigint, p_roles text[])
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $function$
    SELECT EXISTS (
        SELECT 1
        FROM app.course_memberships AS membership
        WHERE membership.course_id = p_course_id
          AND membership.user_id = (SELECT auth.uid())
          AND membership.role = ANY (p_roles)
    )
$function$;

REVOKE ALL ON FUNCTION internal.has_course_role(bigint, text[]) FROM PUBLIC;

-- Core member-readable curriculum; teacher updates only.
ALTER TABLE app.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.courses FORCE ROW LEVEL SECURITY;
CREATE POLICY courses__member_select ON app.courses FOR SELECT TO authenticated
    USING ((SELECT internal.has_course_role(id, ARRAY['student', 'teacher'])));
CREATE POLICY courses__teacher_update ON app.courses FOR UPDATE TO authenticated
    USING ((SELECT internal.has_course_role(id, ARRAY['teacher'])))
    WITH CHECK ((SELECT internal.has_course_role(id, ARRAY['teacher'])));

ALTER TABLE app.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.documents FORCE ROW LEVEL SECURITY;
CREATE POLICY documents__member_select ON app.documents FOR SELECT TO authenticated
    USING ((SELECT internal.has_course_role(course_id, ARRAY['student', 'teacher'])));
CREATE POLICY documents__teacher_update ON app.documents FOR UPDATE TO authenticated
    USING ((SELECT internal.has_course_role(course_id, ARRAY['teacher'])))
    WITH CHECK ((SELECT internal.has_course_role(course_id, ARRAY['teacher'])));

ALTER TABLE app.subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.subjects FORCE ROW LEVEL SECURITY;
CREATE POLICY subjects__member_select ON app.subjects FOR SELECT TO authenticated
    USING ((SELECT internal.has_course_role(course_id, ARRAY['student', 'teacher'])));
CREATE POLICY subjects__teacher_update ON app.subjects FOR UPDATE TO authenticated
    USING ((SELECT internal.has_course_role(course_id, ARRAY['teacher'])))
    WITH CHECK ((SELECT internal.has_course_role(course_id, ARRAY['teacher'])));

ALTER TABLE app.concepts ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.concepts FORCE ROW LEVEL SECURITY;
CREATE POLICY concepts__member_select ON app.concepts FOR SELECT TO authenticated
    USING ((SELECT internal.has_course_role(course_id, ARRAY['student', 'teacher'])));
CREATE POLICY concepts__teacher_update ON app.concepts FOR UPDATE TO authenticated
    USING ((SELECT internal.has_course_role(course_id, ARRAY['teacher'])))
    WITH CHECK ((SELECT internal.has_course_role(course_id, ARRAY['teacher'])));

ALTER TABLE app.problems ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.problems FORCE ROW LEVEL SECURITY;
CREATE POLICY problems__member_select ON app.problems FOR SELECT TO authenticated
    USING ((SELECT internal.has_course_role(course_id, ARRAY['student', 'teacher'])));
CREATE POLICY problems__teacher_update ON app.problems FOR UPDATE TO authenticated
    USING ((SELECT internal.has_course_role(course_id, ARRAY['teacher'])))
    WITH CHECK ((SELECT internal.has_course_role(course_id, ARRAY['teacher'])));

ALTER TABLE app.course_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.course_memberships FORCE ROW LEVEL SECURITY;
CREATE POLICY course_memberships__self_or_teacher_select ON app.course_memberships
    FOR SELECT TO authenticated USING (
        user_id = (SELECT auth.uid())
        OR (SELECT internal.has_course_role(course_id, ARRAY['teacher']))
    );

ALTER TABLE app.course_invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.course_invites FORCE ROW LEVEL SECURITY;
CREATE POLICY course_invites__teacher_all ON app.course_invites FOR ALL TO authenticated
    USING ((SELECT internal.has_course_role(course_id, ARRAY['teacher'])))
    WITH CHECK ((SELECT internal.has_course_role(course_id, ARRAY['teacher'])));

ALTER TABLE app.uploads ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.uploads FORCE ROW LEVEL SECURITY;
CREATE POLICY uploads__teacher_all ON app.uploads FOR ALL TO authenticated
    USING ((SELECT internal.has_course_role(course_id, ARRAY['teacher'])))
    WITH CHECK ((SELECT internal.has_course_role(course_id, ARRAY['teacher'])));

ALTER TABLE app.authored_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.authored_sets FORCE ROW LEVEL SECURITY;
CREATE POLICY authored_sets__teacher_all ON app.authored_sets FOR ALL TO authenticated
    USING ((SELECT internal.has_course_role(course_id, ARRAY['teacher'])))
    WITH CHECK ((SELECT internal.has_course_role(course_id, ARRAY['teacher'])));

ALTER TABLE app.chat_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.chat_sessions FORCE ROW LEVEL SECURITY;
CREATE POLICY chat_sessions__owner_all ON app.chat_sessions FOR ALL TO authenticated
    USING (
        user_id = (SELECT auth.uid())
        AND (SELECT internal.has_course_role(course_id, ARRAY['student', 'teacher']))
    )
    WITH CHECK (
        user_id = (SELECT auth.uid())
        AND (SELECT internal.has_course_role(course_id, ARRAY['student', 'teacher']))
    );

ALTER TABLE app.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.chat_messages FORCE ROW LEVEL SECURITY;
CREATE POLICY chat_messages__owner_select ON app.chat_messages FOR SELECT TO authenticated
    USING (EXISTS (
        SELECT 1 FROM app.chat_sessions AS parent
        WHERE parent.id = chat_session_id AND parent.user_id = (SELECT auth.uid())
    ));
CREATE POLICY chat_messages__owner_insert ON app.chat_messages FOR INSERT TO authenticated
    WITH CHECK (EXISTS (
        SELECT 1 FROM app.chat_sessions AS parent
        WHERE parent.id = chat_session_id
          AND parent.course_id = course_id
          AND parent.user_id = (SELECT auth.uid())
    ));

-- Learner-owned tutoring records: owner writes, owner/teacher reads.
ALTER TABLE app.tutoring_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.tutoring_sessions FORCE ROW LEVEL SECURITY;
CREATE POLICY tutoring_sessions__owner_or_teacher_select ON app.tutoring_sessions
    FOR SELECT TO authenticated USING (
        (user_id = (SELECT auth.uid()) AND
         (SELECT internal.has_course_role(course_id, ARRAY['student', 'teacher'])))
        OR (SELECT internal.has_course_role(course_id, ARRAY['teacher']))
    );
CREATE POLICY tutoring_sessions__owner_insert ON app.tutoring_sessions FOR INSERT TO authenticated
    WITH CHECK (user_id = (SELECT auth.uid()) AND
                (SELECT internal.has_course_role(course_id, ARRAY['student', 'teacher'])));
CREATE POLICY tutoring_sessions__owner_update ON app.tutoring_sessions FOR UPDATE TO authenticated
    USING (user_id = (SELECT auth.uid()) AND
           (SELECT internal.has_course_role(course_id, ARRAY['student', 'teacher'])))
    WITH CHECK (user_id = (SELECT auth.uid()) AND
                (SELECT internal.has_course_role(course_id, ARRAY['student', 'teacher'])));

ALTER TABLE app.tutoring_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.tutoring_messages FORCE ROW LEVEL SECURITY;
CREATE POLICY tutoring_messages__owner_or_teacher_select ON app.tutoring_messages
    FOR SELECT TO authenticated USING (EXISTS (
        SELECT 1 FROM app.tutoring_sessions AS parent
        WHERE parent.id = session_id AND (
            parent.user_id = (SELECT auth.uid())
            OR (SELECT internal.has_course_role(parent.course_id, ARRAY['teacher']))
        )
    ));
CREATE POLICY tutoring_messages__owner_insert ON app.tutoring_messages FOR INSERT TO authenticated
    WITH CHECK (EXISTS (
        SELECT 1 FROM app.tutoring_sessions AS parent
        WHERE parent.id = session_id AND parent.course_id = course_id
          AND parent.user_id = (SELECT auth.uid())
    ));
CREATE POLICY tutoring_messages__owner_update ON app.tutoring_messages FOR UPDATE TO authenticated
    USING (EXISTS (
        SELECT 1 FROM app.tutoring_sessions AS parent
        WHERE parent.id = session_id AND parent.user_id = (SELECT auth.uid())
    ))
    WITH CHECK (EXISTS (
        SELECT 1 FROM app.tutoring_sessions AS parent
        WHERE parent.id = session_id AND parent.course_id = course_id
          AND parent.user_id = (SELECT auth.uid())
    ));

ALTER TABLE app.problem_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.problem_attempts FORCE ROW LEVEL SECURITY;
CREATE POLICY problem_attempts__owner_or_teacher_select ON app.problem_attempts
    FOR SELECT TO authenticated USING (
        (user_id = (SELECT auth.uid()) AND
         (SELECT internal.has_course_role(course_id, ARRAY['student', 'teacher'])))
        OR (SELECT internal.has_course_role(course_id, ARRAY['teacher']))
    );
CREATE POLICY problem_attempts__owner_insert ON app.problem_attempts FOR INSERT TO authenticated
    WITH CHECK (user_id = (SELECT auth.uid()) AND
                (SELECT internal.has_course_role(course_id, ARRAY['student', 'teacher'])));
CREATE POLICY problem_attempts__owner_update ON app.problem_attempts FOR UPDATE TO authenticated
    USING (user_id = (SELECT auth.uid()) AND
           (SELECT internal.has_course_role(course_id, ARRAY['student', 'teacher'])))
    WITH CHECK (user_id = (SELECT auth.uid()) AND
                (SELECT internal.has_course_role(course_id, ARRAY['student', 'teacher'])));

ALTER TABLE app.question_opportunities ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.question_opportunities FORCE ROW LEVEL SECURITY;
CREATE POLICY question_opportunities__owner_or_teacher_select ON app.question_opportunities
    FOR SELECT TO authenticated USING (EXISTS (
        SELECT 1 FROM app.problem_attempts AS parent
        WHERE parent.id = attempt_id AND (
            parent.user_id = (SELECT auth.uid())
            OR (SELECT internal.has_course_role(parent.course_id, ARRAY['teacher']))
        )
    ));
CREATE POLICY question_opportunities__owner_insert ON app.question_opportunities
    FOR INSERT TO authenticated WITH CHECK (EXISTS (
        SELECT 1 FROM app.problem_attempts AS parent
        WHERE parent.id = attempt_id AND parent.course_id = course_id
          AND parent.user_id = (SELECT auth.uid())
    ));
CREATE POLICY question_opportunities__owner_update ON app.question_opportunities
    FOR UPDATE TO authenticated USING (EXISTS (
        SELECT 1 FROM app.problem_attempts AS parent
        WHERE parent.id = attempt_id AND parent.user_id = (SELECT auth.uid())
    ))
    WITH CHECK (EXISTS (
        SELECT 1 FROM app.problem_attempts AS parent
        WHERE parent.id = attempt_id AND parent.course_id = course_id
          AND parent.user_id = (SELECT auth.uid())
    ));

ALTER TABLE app.student_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.student_progress FORCE ROW LEVEL SECURITY;
CREATE POLICY student_progress__owner_or_teacher_select ON app.student_progress
    FOR SELECT TO authenticated USING (
        user_id = (SELECT auth.uid())
        OR (SELECT internal.has_course_role(course_id, ARRAY['teacher']))
    );

ALTER TABLE app.learner_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.learner_state FORCE ROW LEVEL SECURITY;
CREATE POLICY learner_state__owner_or_teacher_select ON app.learner_state
    FOR SELECT TO authenticated USING (
        user_id = (SELECT auth.uid())
        OR (SELECT internal.has_course_role(course_id, ARRAY['teacher']))
    );

ALTER TABLE app.mastery_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.mastery_events FORCE ROW LEVEL SECURITY;
CREATE POLICY mastery_events__owner_or_teacher_select ON app.mastery_events
    FOR SELECT TO authenticated USING (
        user_id = (SELECT auth.uid())
        OR (SELECT internal.has_course_role(course_id, ARRAY['teacher']))
    );

ALTER TABLE app.learner_entities ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.learner_entities FORCE ROW LEVEL SECURITY;
CREATE POLICY learner_entities__member_select ON app.learner_entities FOR SELECT TO authenticated
    USING ((SELECT internal.has_course_role(course_id, ARRAY['student', 'teacher'])));
CREATE POLICY learner_entities__teacher_update ON app.learner_entities FOR UPDATE TO authenticated
    USING ((SELECT internal.has_course_role(course_id, ARRAY['teacher'])))
    WITH CHECK ((SELECT internal.has_course_role(course_id, ARRAY['teacher'])));

ALTER TABLE app.learner_negotiations ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.learner_negotiations FORCE ROW LEVEL SECURITY;
CREATE POLICY learner_negotiations__owner_or_teacher_select ON app.learner_negotiations
    FOR SELECT TO authenticated USING (
        user_id = (SELECT auth.uid())
        OR (SELECT internal.has_course_role(course_id, ARRAY['teacher']))
    );
CREATE POLICY learner_negotiations__owner_insert ON app.learner_negotiations
    FOR INSERT TO authenticated WITH CHECK (
        user_id = (SELECT auth.uid())
        AND (SELECT internal.has_course_role(course_id, ARRAY['student', 'teacher']))
    );

ALTER TABLE app.ai_usage_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.ai_usage_reports FORCE ROW LEVEL SECURITY;
CREATE POLICY ai_usage_reports__owner_select ON app.ai_usage_reports FOR SELECT TO authenticated
    USING (user_id = (SELECT auth.uid()));
CREATE POLICY ai_usage_reports__owner_insert ON app.ai_usage_reports FOR INSERT TO authenticated
    WITH CHECK (
        user_id = (SELECT auth.uid())
        AND (SELECT internal.has_course_role(course_id, ARRAY['student', 'teacher']))
        AND EXISTS (
            SELECT 1 FROM app.chat_sessions AS parent
            WHERE parent.external_id = chat_id
              AND parent.user_id = (SELECT auth.uid())
              AND parent.course_id = course_id
        )
    );

-- -------------------------------------------------------------------------
-- Privileges: app is policy-protected; internal is explicitly service-only.
-- -------------------------------------------------------------------------

REVOKE ALL ON SCHEMA app FROM PUBLIC, anon;
GRANT USAGE ON SCHEMA app TO authenticated, app_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA app TO authenticated, app_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA app TO authenticated, app_runtime;

REVOKE ALL ON SCHEMA internal FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL TABLES IN SCHEMA internal FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA internal FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL ROUTINES IN SCHEMA internal FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA internal
    REVOKE ALL ON TABLES FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA internal
    REVOKE ALL ON SEQUENCES FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA internal
    REVOKE ALL ON ROUTINES FROM PUBLIC, anon, authenticated;

GRANT USAGE ON SCHEMA internal TO authenticated, app_runtime;
GRANT EXECUTE ON FUNCTION internal.has_course_role(bigint, text[])
    TO authenticated, app_runtime;

DO $postconditions$
DECLARE
    app_table_count integer;
    internal_table_count integer;
    unprotected_app_tables text;
BEGIN
    SELECT count(*) INTO app_table_count
    FROM pg_tables WHERE schemaname = 'app';
    SELECT count(*) INTO internal_table_count
    FROM pg_tables WHERE schemaname = 'internal';

    IF app_table_count <> 21 OR internal_table_count <> 12 THEN
        RAISE EXCEPTION 'DB-04 postcondition failed: expected 21 app + 12 internal tables, got % + %',
            app_table_count, internal_table_count;
    END IF;

    SELECT string_agg(format('%I.%I', n.nspname, c.relname), ', ' ORDER BY c.relname)
    INTO unprotected_app_tables
    FROM pg_class AS c
    JOIN pg_namespace AS n ON n.oid = c.relnamespace
    WHERE n.nspname = 'app'
      AND c.relkind = 'r'
      AND (NOT c.relrowsecurity OR NOT c.relforcerowsecurity);

    IF unprotected_app_tables IS NOT NULL THEN
        RAISE EXCEPTION 'DB-04 postcondition failed: app tables without forced RLS: %',
            unprotected_app_tables;
    END IF;
END
$postconditions$;

COMMIT;
