"""Bounded chat-history loader (item #2).

Replaces the V2 "load every message every turn" pattern. Two changes:
- Last `RAW_WINDOW_TURNS` turns are passed to the model verbatim.
- Older turns are condensed into a rolling `history_summary` stored on
  TutoringSession. The summary is refreshed when the unwindowed tail has
  grown by `REFRESH_EVERY_K_TURNS` since the last refresh, so each turn
  doesn't pay for a fresh summarization.

The summary is generated by `apollo.agent._llm.cheap_chat`. Soft-fails
to "no summary" on error: the caller still gets the raw window, just
without the older context. Long sessions briefly lose memory; subsequent
turns recover.
"""
from __future__ import annotations

import json
import logging

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from apollo.agent._llm import cheap_chat
from apollo.persistence.models import TutoringSession, TutoringMessage

_LOG = logging.getLogger(__name__)

RAW_WINDOW_TURNS: int = 12
REFRESH_EVERY_K_TURNS: int = 8


_SUMMARIZER_PROMPT = """You compress a tutoring conversation into a short
note that the assistant can use to remember context.

You will receive a sequence of (role, content) turns. Produce a 3-6 line
summary capturing:
- what the student has tried to teach so far,
- where they were confused or got stuck,
- any equations, definitions, or conditions that appeared.

Keep it factual and student-voiced — do not introduce concepts the
student has not named. Return ONLY a JSON object: {"summary": "..."}.
"""


async def _all_messages(
    db: AsyncSession, session_id: int, attempt_id: int | None,
) -> list[TutoringMessage]:
    result = await db.execute(
        select(TutoringMessage)
        .where(TutoringMessage.session_id == session_id)
        .where(TutoringMessage.attempt_id == attempt_id)
        .order_by(TutoringMessage.turn_index)
    )
    return list(result.scalars().all())


def _format_for_llm(messages: list[TutoringMessage]) -> list[dict[str, str]]:
    out: list[dict[str, str]] = []
    for m in messages:
        role = "user" if m.role == "student" else "assistant"
        out.append({"role": role, "content": m.content})
    return out


def _summarize(turns: list[TutoringMessage]) -> str | None:
    """Generate a rolling summary. Soft-fails to None on any error."""
    if not turns:
        return None
    payload = {
        "turns": [
            {"role": "user" if m.role == "student" else "assistant",
             "content": m.content}
            for m in turns
        ],
    }
    try:
        raw = cheap_chat(
            purpose="history_summarizer",
            messages=[
                {"role": "system", "content": _SUMMARIZER_PROMPT},
                {"role": "user", "content": json.dumps(payload)},
            ],
            response_format={"type": "json_object"},
            temperature=0.0,
        )
        parsed = json.loads(raw)
    except Exception as exc:  # noqa: BLE001
        _LOG.warning("history_summarizer soft-fail: %s", exc)
        return None
    summary = parsed.get("summary")
    if isinstance(summary, str) and summary.strip():
        return summary.strip()
    return None


async def load_windowed_history(
    *,
    db: AsyncSession,
    session: TutoringSession,
    attempt_id: int | None,
) -> tuple[str | None, list[dict[str, str]]]:
    """Return `(summary_or_none, raw_window)` for one attempt only.

    Side effect: refreshes `session.history_summary` /
    `session.history_summary_up_to_turn` and commits when a refresh fires.
    """
    messages = await _all_messages(db, session.id, attempt_id)
    total = len(messages)

    if total <= RAW_WINDOW_TURNS:
        return None, _format_for_llm(messages)

    # We have older turns — figure out if we need a fresh summary.
    cutoff = total - RAW_WINDOW_TURNS  # number of older turns
    older = messages[:cutoff]
    last_older_turn = older[-1].turn_index

    last_covered = session.history_summary_up_to_turn or -1
    needs_refresh = (
        session.history_summary is None
        or last_older_turn - last_covered >= REFRESH_EVERY_K_TURNS
    )

    if needs_refresh:
        new_summary = _summarize(older)
        if new_summary is not None:
            session.history_summary = new_summary
            session.history_summary_up_to_turn = last_older_turn
            await db.commit()

    raw_window = _format_for_llm(messages[cutoff:])
    return session.history_summary, raw_window


__all__ = [
    "RAW_WINDOW_TURNS",
    "REFRESH_EVERY_K_TURNS",
    "load_windowed_history",
]
